"use client";
import { useMemo, useRef, useState, useSyncExternalStore } from "react";
import { DstField, dstControlClassName } from "@/app/components/dst-field";
import { PhamNhanItemCard } from "@/app/components/pham-nhan-item-card";
import { filterPhamNhanItems, type PhamNhanItem, type PhamNhanSnapshot } from "@/app/lib/pham-nhan";

const PAGE_SIZE = 12;
const sections = [{ id: "items", label: "Vật phẩm" }, { id: "affixes", label: "Affix" }, { id: "guides", label: "Hướng dẫn" }, { id: "config", label: "Config" }];
const subscribe = (callback: () => void) => { window.addEventListener("hashchange", callback); return () => window.removeEventListener("hashchange", callback); };

export function PhamNhanBrowser({ data }: { data: PhamNhanSnapshot }) {
  const hash = useSyncExternalStore(subscribe, () => window.location.hash, () => "#sec=items");
  const params = new URLSearchParams(hash.slice(1));
  const section = sections.some((entry) => entry.id === params.get("sec")) ? params.get("sec")! : "items";
  const selected = data.items.find((item) => item.id === params.get("item"));
  const opener = useRef<HTMLButtonElement | null>(null);
  const [query, setQuery] = useState(""); const [category, setCategory] = useState("all"); const [page, setPage] = useState(1);
  const results = useMemo(() => filterPhamNhanItems(data.items, query, category), [data.items, query, category]);
  const pages = Math.max(1, Math.ceil(results.length / PAGE_SIZE)); const currentPage = Math.min(page, pages);
  const updateQuery = (nextQuery: string) => { setQuery(nextQuery); setPage(1); };
  const updateCategory = (nextCategory: string) => { setCategory(nextCategory); setPage(1); };
  const navigate = (next: string, item?: string) => { window.history.replaceState(null, "", `#sec=${next}${item ? `&item=${encodeURIComponent(item)}` : ""}`); window.dispatchEvent(new Event("hashchange")); };
  const open = (item: PhamNhanItem, button: HTMLButtonElement) => { opener.current = button; navigate("items", item.id); };
  const close = () => { navigate("items"); opener.current?.focus(); };
  const body = section === "items" ? <><div className="mb-5 grid gap-3 sm:grid-cols-2"><DstField label="Tìm trong Phàm Nhân" htmlFor="pham-nhan-search"><input id="pham-nhan-search" aria-label="Tìm trong Phàm Nhân" type="search" value={query} onChange={(event) => updateQuery(event.target.value)} className={dstControlClassName} /></DstField><DstField label="Loại vật phẩm" htmlFor="pham-nhan-category"><select id="pham-nhan-category" value={category} onChange={(event) => updateCategory(event.target.value)} className={dstControlClassName}><option value="all">Tất cả</option>{[...new Set(data.items.map((item) => item.category))].sort().map((value) => <option key={value} value={value}>{value}</option>)}</select></DstField></div><div className="grid gap-4 lg:grid-cols-2">{results.slice((currentPage - 1) * PAGE_SIZE, currentPage * PAGE_SIZE).map((item) => <PhamNhanItemCard key={item.id} item={item} onOpen={open} />)}</div>{pages > 1 ? <nav aria-label="Phân trang vật phẩm" className="mt-6 flex items-center justify-between"><button type="button" disabled={currentPage === 1} onClick={() => setPage(currentPage - 1)} className="min-h-11 rounded-xl border border-nova-border px-4 disabled:opacity-40">← Trước</button><span>Trang {currentPage} / {pages}</span><button type="button" disabled={currentPage === pages} onClick={() => setPage(currentPage + 1)} className="min-h-11 rounded-xl border border-nova-border px-4 disabled:opacity-40">Sau →</button></nav> : null}</> : section === "affixes" ? <div className="space-y-3">{data.affixes.map((entry) => <article key={entry.id} className="rounded-2xl border border-nova-border bg-nova-surface-soft p-4"><h2 className="font-semibold">{entry.name}</h2><p className="text-sm text-nova-muted">{entry.description}</p></article>)}</div> : section === "guides" ? <div className="space-y-3">{data.guides.map((entry) => <article key={entry.id} className="rounded-2xl border border-nova-border bg-nova-surface-soft p-4"><h2 className="font-semibold">{entry.title}</h2><p className="mt-2 whitespace-pre-line text-sm leading-6 text-nova-muted">{entry.text}</p></article>)}</div> : <div className="space-y-3">{data.config.map((entry) => <article key={entry.key} className="rounded-2xl border border-nova-border bg-nova-surface-soft p-4"><h2 className="font-semibold">{entry.label}</h2><p className="text-sm text-nova-muted">{entry.description}</p><p className="mt-2 text-sm">Mặc định: {String(entry.default)}</p></article>)}</div>;
  return <div className="mt-8 grid min-w-0 items-start gap-6 lg:grid-cols-[220px_minmax(0,1fr)]"><aside className="rounded-2xl border border-nova-border bg-nova-surface p-3 lg:sticky lg:top-4"><p className="px-3 py-2 text-xs font-semibold uppercase tracking-widest text-nova-muted">Mục lục Phàm Nhân</p><nav aria-label="Mục lục Phàm Nhân" className="flex gap-1 overflow-x-auto lg:flex-col">{sections.map((entry) => <button key={entry.id} type="button" aria-pressed={section === entry.id} onClick={() => navigate(entry.id)} className={`min-h-11 shrink-0 cursor-pointer rounded-xl px-3 py-2 text-left text-sm font-semibold focus-visible:outline-2 focus-visible:outline-nova-accent ${section === entry.id ? "bg-nova-accent text-white" : "text-nova-muted hover:bg-nova-surface-soft"}`}>{entry.label}</button>)}</nav></aside><section className="min-w-0">{body}</section>{selected ? <div role="dialog" aria-modal="true" aria-label={selected.name} onKeyDown={(event) => { if (event.key === "Escape") close(); }} tabIndex={-1} className="fixed inset-0 z-50 grid place-items-center bg-black/60 p-4"><div className="max-h-[85vh] w-full max-w-xl overflow-auto rounded-2xl bg-nova-surface p-5"><button type="button" onClick={close} className="float-right min-h-11 rounded-xl border border-nova-border px-3">Đóng</button><h2 className="text-xl font-semibold">{selected.name}</h2><p className="mt-3 text-nova-muted">{selected.description}</p></div></div> : null}</div>;
}
