import type { BossGuide } from './guide-types';

export const surfaceGuides: BossGuide[] = [
  {
    slug: 'bee-queen',
    title: 'Bee Queen: từ chuẩn bị tổ ong đến mở Bundling Wrap',
    description: 'Chuẩn bị mũ chuyên dụng, điều khiển đàn ong và vượt bốn giai đoạn của Ong Chúa.',
    difficulty: 'Khó • dễ tổ chức hơn khi có đồng đội',
    location: 'Gigantic Beehive trên mặt đất',
    summary: 'Mục tiêu của chuyến đi đầu tiên là bản vẽ Bundling Wrap. Hãy chuẩn bị cho một trận tiêu hao dài; lượng ong và khả năng kiểm soát khoảng trống quan trọng hơn việc cố đánh thêm một nhát.',
    preparations: [
      'Hammer để gọi boss; đánh dấu tổ lớn và dọn một lối chạy rộng trước trận.',
      'Nhiều Beekeeper Hat, Ham Bat mới, thức ăn hồi máu và nguồn sáng đặt sẵn.',
      'Phương án phổ thông có kiểm soát: chuẩn bị ít nhất hai Pan Flutes đủ lượt, thêm Walking Cane nếu có; đi một mình vẫn cần nhiều dự trữ vì trận dài.',
      'Để mũ thay và đồ hồi máu ở ô dễ dùng; thống nhất người kéo ong nếu chơi nhóm.',
    ],
    sections: [
      {
        id: 'find-hive', title: '1. Tìm tổ và chuẩn bị đường chạy',
        paragraphs: ['Tìm Gigantic Beehive: tổ ong lớn nổi bật trong vùng đồng cỏ có nhiều tổ ong. Đánh dấu vị trí rồi về chuẩn bị; đừng thử đập tổ chỉ để xem có gì bên trong khi chưa có giáp. Hammer nhiều lần sẽ đánh thức Ong Chúa, và ngay cả việc lấy mật cũng có nguy cơ gọi boss.'],
        steps: ['Khảo sát một vòng quanh tổ vào ban ngày. Chọn khoảng đất rộng, tránh bờ biển và vật cản làm mất lối thoát.', 'Đặt nguồn sáng và đồ dự phòng ở vị trí có thể quay lại mà không phải chạy xuyên qua tổ. Đi thử cả đường vòng trước khi bắt đầu.', 'Ăn đầy, mặc mũ, cầm sẵn vũ khí rồi mới dùng Hammer. Khi boss xuất hiện, chuyển ngay sang vũ khí.'],
        sources: [{ page: 'Gigantic_Beehive' }],
      },
      {
        id: 'equipment', title: '2. Làm trang bị từ nguồn dễ kiếm',
        paragraphs: ['Beekeeper Hat cần 8 Silk và 1 Rope, mở công thức tại Alchemy Engine. Mũ giảm sát thương từ các loại ong, bao gồm Ong Chúa; hãy đem nhiều chiếc thay vì đặt cược vào một chiếc gần hỏng. Silk lấy từ nhện, nên chuẩn bị nguồn tơ trước ngày đi đánh.', 'Pan Flute cần 5 Cut Reeds + 1 Mandrake + 1 Rope, học tại Prestihatitator. Dành sáo cho lúc đàn tăng áp lực; không đợi đã bị bao vây mới bắt đầu thổi. Walking Cane giúp chạy và đổi vị trí: dùng 1 Walrus Tusk từ MacTusk mùa đông + 2 Gold Nuggets + 4 Twigs tại Alchemy Engine, đổi sang vũ khí khi đánh.'],
        steps: ['Làm Ham Bat sát giờ khởi hành: 1 Pig Skin, 2 Meat và 2 Twigs. Vũ khí này không hao theo số lần đánh nhưng yếu dần khi cũ.', 'Dành một buổi riêng để nấu hồi máu. Một công thức Pierogi dễ kiểm soát là 1 Meat hoặc Monster Meat, 1 Egg và 2 Carrot; không thay rau bằng Pepper.', 'Sắp mũ mới ngay cạnh mũ đang dùng trong túi. Tập thay mũ khi đang di chuyển trước khi đối diện cả đàn ong.'],
        sources: [{ page: 'Beekeeper_Hat/DST' }, { page: 'Ham_Bat' }, { page: 'Pierogi' }, { page: 'Pan_Flute' }, { page: 'Walking_Cane' }],
      },
      {
        id: 'first-half', title: '3. Nửa đầu: học cách tách đàn ong',
        paragraphs: ['Trên 75% máu, Ong Chúa gọi đàn đầu; từ 75% xuống 50%, đàn đông hơn. Đừng đứng giữa boss và toàn bộ ong con. Mục tiêu là kéo chúng thành hàng, có khoảng trống để quay lại đánh.'],
        steps: ['Quan sát vị trí ong trước khi áp sát. Nếu chúng đang kẹp hai phía, chạy ra khoảng đất đã dọn rồi mới quay lại.', 'Chỉ đánh khi đường rút còn mở. Thấy nhiều ong áp đến cùng lúc thì ngừng đánh, di chuyển rồi kiểm tra máu và mũ.', 'Chơi nhóm: một người dẫn đàn, người còn lại đánh boss. Báo trước khi đổi vai để không kéo đàn xuyên qua đồng đội đang hồi máu.'],
        tips: ['Đầu trận, giữ lại một Grumble Bee có thể hạn chế việc gọi đàn mới; đây không phải cách khóa cơ chế cho toàn bộ trận.'],
        sources: [{ page: 'Bee_Queen' }, { page: 'Grumble_Bee' }],
      },
      {
        id: 'screech', title: '4. Nửa sau: nghe tiếng hét rồi đổi nhịp',
        paragraphs: ['Dưới 50%, tiếng hét tăng sức ép từ ong con; dưới 25%, tiếng hét dày hơn. Vệt mật làm chậm nên phải nhìn cả mặt đất. Khi đàn tăng áp lực, dùng Pan Flute trong tầm để ngủ cả boss và ong, rồi tập trung đánh Ong Chúa. Đây chỉ là cửa sổ tạm: theo dõi lúc đàn thức và giữ lượt sáo cho vòng sau.'],
        steps: ['Khi đàn lao tới, chạy theo lối rộng. Chờ có khoảng trống rõ ràng rồi vòng lại; không quay đầu ngay vào giữa đàn.', 'Mỗi lần quay lại chỉ tận dụng cửa sổ an toàn hiện có. Nếu ong đã khép lại, bỏ lượt đánh ấy và tổ chức lại vị trí.', 'Hồi máu sớm khi đã tạo khoảng cách. Trong nhóm, gọi rõ “thay mũ” hoặc “hồi máu” để người khác không đổi hướng kéo ong vào mình.'],
        tips: ['Không có số nhát đánh cố định áp dụng cho mọi nhân vật, tốc độ di chuyển và độ trễ mạng.'],
        sources: [{ page: 'Bee_Queen' }, { page: 'Grumble_Bee' }],
      },
      {
        id: 'rewards', title: '5. Biến chiến thắng thành kho thực phẩm',
        paragraphs: ['Học bản vẽ Bundling Wrap trước khi cất chiến lợi phẩm. Mỗi lần chế cần 1 Wax Paper và 1 Rope; gói chứa tối đa bốn chồng vật phẩm và ngừng sự hư hỏng của thức ăn bên trong. Khi mở, lấy lại Wax Paper để dùng tiếp.'],
        steps: ['Tách đồ dùng ngay khỏi phần muốn bảo quản. Đồ hồi máu dành cho chuyến sau nên gói riêng để dễ lấy.', 'Không gói toàn bộ đồ ăn đang cần giữa chuyến đi. Việc mở gói thả đồ xuống đất, nên chọn chỗ an toàn và đủ chỗ trong túi.', 'Giữ Royal Jelly và chiếc vương miện; đừng bỏ quên vật phẩm dưới đống mật và Honeycomb.'],
        sources: [{ page: 'Bundling_Wrap/DST' }, { page: 'Bee_Queen' }],
      },
      {
        id: 'repeat', title: '6. Đánh lại và cải thiện lần sau',
        paragraphs: ['Sau khi thắng, tổ cần khoảng 20 ngày để mọc lại ở thiết lập thường. Nếu chỉ bỏ chạy và boss tự trở về tổ, đó không phải một lần tiêu diệt; có thể gọi lại khi đã chuẩn bị xong.'],
        steps: ['Ghi lại số mũ và phần hồi máu đã dùng. Lần sau mang thêm phần dự phòng dựa trên trận thật của nhóm.', 'Kiểm tra lại ánh sáng và các góc đường chạy; mở rộng nơi từng khiến bạn mắc kẹt.', 'Chỉ lặp trận khi đã bổ sung tơ, thức ăn và vũ khí. Có bản vẽ rồi không có nghĩa các lượt sau sẽ ít nguy hiểm hơn.'],
        sources: [{ page: 'Gigantic_Beehive' }, { page: 'Bee_Queen' }],
      },
    ],
    rewards: [
      { name: 'Bundling Wrap Blueprint', use: 'Mở công thức đóng gói và bảo quản thực phẩm.', page: 'Bundling_Wrap/DST' },
      { name: 'Royal Jelly', use: 'Nguyên liệu chế Jellybeans.', page: 'Royal_Jelly' },
      { name: 'Bee Queen Crown', use: 'Trang bị hữu ích khi đối diện hào quang giảm tinh thần.', page: 'Bee_Queen_Crown' },
    ],
    mistakes: [
      { question: 'Sao đã dọn ong mà chúng vẫn xuất hiện?', answer: 'Grumble Bee là cơ chế của trận. Việc giữ một con chỉ giúp ở đầu trận; đừng dành mọi tài nguyên để tiêu diệt đàn vô tận.' },
      { question: 'Có thể dùng một chiếc mũ rồi đứng đánh tới chết không?', answer: 'Đó không phải kế hoạch đáng tin cho người mới. Mang mũ thay, theo dõi độ bền và dành khoảng trống để hồi máu.' },
      { question: 'Có cần chọn đúng nhân vật mới thắng được?', answer: 'Không, nhưng lượng tài nguyên và cách điều khiển đàn khác nhau. Tuyến này dùng đồ phổ thông; kỹ năng riêng của nhân vật là phần bổ sung.' },
    ],
    next: [{ label: 'Chuẩn bị trận Dragonfly', href: '/bosses/dragonfly' }, { label: 'Thử tuyến Klaus mùa đông', href: '/bosses/klaus' }],
  },
  {
    slug: 'dragonfly', title: 'Dragonfly: dựng bãi đánh, chặn Lavae và xử lý cuồng nộ',
    description: 'Lộ trình Dragonfly bản Together, từ giáp và sáo ngủ đến Scaled Furnace.',
    difficulty: 'Khó • cần chuẩn bị bãi và đồ kiểm soát',
    location: 'Sa mạc Dragonfly có các hồ dung nham',
    summary: 'Đây là boss thường trú của sa mạc trong DST. Chọn bãi đánh trước, chuẩn bị Pan Flute và coi các đợt Lavae là tín hiệu đổi công việc: ngừng đuổi boss, kiểm tra phòng thủ, rồi xử lý cuồng nộ.',
    preparations: ['Ham Bat mới hoặc vũ khí tương đương, nhiều giáp/mũ dự phòng và đồ hồi máu.', 'Pan Flute còn nhiều lượt; đặt ở ô thao tác nhanh.', 'Stone Wall để chặn Lavae, nguồn sáng và phương án giữ nhiệt theo mùa.'],
    sections: [
      {
        id: 'locate', title: '1. Nhận diện đúng sa mạc',
        paragraphs: ['Tìm cụm hồ dung nham và Dragonfly đang bay gần đó. Trong DST không cần chờ mùa hè hay vật phẩm triệu hồi. Đừng nhầm với cơ chế boss mùa hè của bản chơi đơn.'],
        steps: ['Khảo sát bãi vào ban ngày trước khi gây hấn. Đánh dấu nơi đứng đánh và đường rút, tránh chọn mép biển.', 'Mang vật liệu đến trước, quay về bổ sung rồi mới khai chiến. Tách buổi dựng bãi khỏi buổi đánh giúp tránh khởi đầu với vũ khí cũ và đồ ăn thiếu.', 'Để đồ dự phòng ở nơi dễ tiếp cận nhưng không nằm trong đường chạy. Nếu chơi nhóm, chỉ định trước ai dùng sáo.'],
        sources: [{ page: 'Dragonfly/DST' }],
      },
      {
        id: 'craft', title: '2. Có đủ giáp và sáo trước khi đánh',
        paragraphs: ['Football Helmet cần 1 Pig Skin và 1 Rope, mở tại Alchemy Engine. Pig Skin có thể lấy bằng Hammer từ Pig Head hoặc Pig House; phá nhà đồng nghĩa mất nguồn lợn tại chỗ. Nguồn tái tạo là cho lợn ăn 4 Monster Meat rồi đánh Werepig để lấy da và thịt.'],
        steps: ['Chuẩn bị nhiều mũ hoàn chỉnh. Đừng cộng phần trăm giảm sát thương của các món thành bất tử; vẫn cần hồi máu và thay đồ.', 'Chế Pan Flute bằng 5 Cut Reeds, 1 Mandrake và 1 Rope tại Prestihatitator. Giữ Mandrake cho công thức này nếu chưa có sáo.', 'Cất công cụ khai thác, đưa sáo và hồi máu lên ô dễ bấm. Kiểm tra lượng dùng còn lại ngay tại bãi.'],
        sources: [{ page: 'Football_Helmet/DST' }, { page: 'Pig_Skin/DST' }, { page: 'Pan_Flute' }],
      },
      {
        id: 'arena', title: '3. Tường chặn Lavae, không thay việc né boss',
        paragraphs: ['Một phương án chuẩn bị là dựng tường đá quanh các hồ để chặn Lavae. Kiểm tra từng khe hở; tường đặt tùy tiện dễ để sót đường đi. Không dùng tường gỗ hoặc cỏ gần nguồn lửa.'],
        steps: ['Đi hết chu vi các đoạn tường trước trận. Giữ bên đứng đánh đủ rộng để lùi và quay lại, không tự nhốt mình vào góc.', 'Đặt nguồn sáng để vẫn nhìn rõ đường né khi trời tối. Đừng chờ bóng tối phủ xuống mới lục túi tìm đèn.', 'Đánh gần khu vực tổ; kéo boss đi xa có thể khiến nó trở về và hồi đầy. Không biến một lần né thành cuộc chạy đuổi xuyên sa mạc.'],
        sources: [{ page: 'Dragonfly/DST' }, { page: 'Durability' }],
      },
      {
        id: 'normal-combat', title: '4. Nhịp thường: dụ đòn, lùi rồi đánh',
        paragraphs: ['Hướng thao tác cho người mới: tiến đủ gần để boss bắt đầu đòn quẹt, lùi tránh, rồi quay lại đánh khi hoạt ảnh đã qua. Quan sát thực tế thay vì học một số nhát cố định.'],
        steps: ['Lượt đầu chỉ đánh ngắn để đo độ trễ và khoảng cách. Nếu vừa quay lại đã trúng đòn, giảm thời gian đứng đánh ở lượt sau.', 'Thay mũ trong lúc có khoảng trống, không đợi nó vỡ. Người bị boss nhắm cần giữ hướng di chuyển dễ đoán để đồng đội không phải đuổi vòng quanh.', 'Khi boss bỏ đi gọi Lavae, tận dụng thời gian để hồi máu và kiểm tra sáo. Đừng đuổi sát hồ chỉ vì muốn thêm sát thương.'],
        sources: [{ page: 'Dragonfly/DST' }, { page: 'Football_Helmet/DST' }],
      },
      {
        id: 'lavae', title: '5. Đợt Lavae và cuồng nộ',
        paragraphs: ['Các mốc 80%, 50% và 20% máu kích hoạt Lavae, nhưng có thể có đợt bổ sung. Lavae cuối tự hết đời không bảo đảm boss nổi giận: nó có thể gọi đợt khác. Khi cuồng nộ xuất hiện, dùng Pan Flute trong tầm để đưa boss về trạng thái thường.'],
        steps: ['Người giữ sáo ngừng tham đánh và theo dõi boss. Sáo cần thời gian thực hiện; đừng đợi đang bị đánh liên tục mới sử dụng.', 'Nếu Lavae lọt tường, gọi cả nhóm đổi vị trí và xử lý tình huống trước. Không đứng trong lửa chỉ vì bãi đã được chuẩn bị từ trước.', 'Sau khi boss ngủ, kiểm tra nhanh máu và giáp rồi mới tiếp tục. Giữ lượt sáo dự phòng, đừng phân phối tài nguyên theo giả định trận chỉ có ba lần chuyển pha.'],
        sources: [{ page: 'Dragonfly/DST' }, { page: 'Pan_Flute' }],
      },
      {
        id: 'furnace', title: '6. Thu chiến lợi phẩm và làm lò',
        paragraphs: ['Học bản vẽ Scaled Furnace, giữ Scales và đá quý. Lò cần 2 Red Gems, 10 Charcoal và 1 Scales; đây là nguồn nhiệt lâu dài không cần tiếp nhiên liệu. Đặt nó có tính toán vì đứng gần có thể quá nóng.'],
        steps: ['Đặt lò ở khu sưởi riêng, chừa lối đi để mùa nóng không phải chạy sát lò.', 'Bốn ô của lò là nơi tiêu hủy vật phẩm, không phải rương. Không cho chiến lợi phẩm quý vào để cất tạm.', 'Sửa tường và bổ sung sáo sau trận. Ở thiết lập mặc định Dragonfly trở lại sau 20 ngày; thiết lập thế giới có thể thay đổi thời gian này.'],
        sources: [{ page: 'Scaled_Furnace' }, { page: 'Dragonfly/DST' }],
      },
    ],
    rewards: [{ name: 'Scales', use: 'Vật liệu trang bị và Scaled Furnace.', page: 'Scales' }, { name: 'Scaled Furnace Blueprint', use: 'Mở nguồn nhiệt thường trực cho căn cứ.', page: 'Scaled_Furnace' }, { name: 'Đá quý nhiều màu', use: 'Dự trữ cho chế tạo ma thuật và các chuyến thám hiểm sau.', page: 'Dragonfly/DST' }],
    mistakes: [
      { question: 'Tại sao boss tự hồi đầy?', answer: 'Có thể đã bị kéo quá xa bãi hoặc thế giới/server được khởi động lại. Giữ giao tranh quanh tổ và chuẩn bị đánh liền mạch.' },
      { question: 'Có tường rồi có thể bỏ Pan Flute không?', answer: 'Tường chỉ hỗ trợ chặn Lavae. Cần một cách xử lý cuồng nộ; tuyến này dùng Pan Flute vì dễ thao tác hơn cho người mới.' },
      { question: 'Lò có phải đèn đủ dùng cả căn cứ không?', answer: 'Không. Vùng sáng rất nhỏ, nên vẫn bố trí ánh sáng riêng cho khu sinh hoạt.' },
    ],
    next: [{ label: 'Mở kho bảo quản với Bee Queen', href: '/bosses/bee-queen' }, { label: 'Đi săn Klaus', href: '/bosses/klaus' }],
  },
  {
    slug: 'klaus', title: 'Klaus: lấy sừng, tránh phép hươu và mở Loot Stash',
    description: 'Lộ trình mùa đông cho người mới, gồm cả lần hồi sinh và đòn chồm ở pha hai.',
    difficulty: 'Khó • cần đọc hoạt ảnh và giữ ấm',
    location: 'Loot Stash trong rừng lá rộng hoặc Mosaic',
    summary: 'Klaus là bài kiểm tra né đòn và chọn mục tiêu. Giữ hai Gem Deer sống, không kéo chúng xa chủ, và chuẩn bị cho hai thanh máu nối tiếp trước khi dùng chiếc sừng chiến lợi phẩm mở túi.',
    preparations: ['Deer Antler từ No-Eyed Deer đã mọc sừng; tìm Loot Stash trước khi gọi.', 'Vũ khí mới, giáp dự phòng, hồi máu và nguồn sáng.', 'Thermal Stone đã sưởi nóng, đồ giữ ấm và một chỗ sưởi chuẩn bị trước.'],
    sections: [
      {
        id: 'antler', title: '1. Kiếm Deer Antler đúng cách',
        paragraphs: ['Tìm đàn No-Eyed Deer ở Mosaic hoặc rừng lá rộng từ mùa thu. Sang mùa đông chúng mọc sừng. Sừng dùng gọi Klaus lấy bằng cách làm hươu chạy va vào cây; đừng giết cả đàn với kỳ vọng nhặt đúng chìa khóa.'],
        steps: ['Quan sát hướng cây và vị trí đàn. Chọn một con đã có sừng với đường chạy thoáng về phía thân cây.', 'Làm nó hoảng chạy, điều chỉnh vị trí để nó va cây rồi nhặt Deer Antler rơi ra.', 'Mang sừng về chuẩn bị đồ. Nếu chưa thấy sừng, kiểm tra mùa và hình dáng hươu; không phải cứ gặp hươu là có thể bắt đầu ngay.'],
        sources: [{ page: 'No-Eyed_Deer' }, { page: 'Deer_Antler' }],
      },
      {
        id: 'winter-kit', title: '2. Chuẩn bị một trận dài giữa mùa đông',
        paragraphs: ['Thermal Stone chế tại Alchemy Engine bằng 10 Rocks, 1 Pickaxe và 3 Flint. Sưởi nó trước khi đi; mang một viên lạnh không giải quyết được rét. Đặt chỗ sưởi trước trận để không phải vừa tìm củi vừa né boss.'],
        steps: ['Chế Ham Bat mới gần giờ đánh, hoặc dùng vũ khí đủ độ bền cho cả hai pha. Để vũ khí thay ở vị trí dễ tìm.', 'Mang nhiều mũ/giáp, đồ hồi máu và thức ăn hồi tinh thần phù hợp nhân vật. Chia riêng phần ăn vì đói với phần dự trữ chữa thương.', 'Kiểm tra ánh sáng tại bãi. Đêm mùa đông dài; giữ được tầm nhìn sẽ giúp nhận ra vùng phép và chọn đường né.', 'Nếu đi nhóm, thống nhất chỉ đánh Klaus. Hạn chế đồng minh hoặc sát thương diện rộng không kiểm soát được gần hai con hươu.'],
        sources: [{ page: 'Thermal_Stone' }, { page: 'Ham_Bat' }, { page: 'Seasons/Winter' }, { page: 'Gem_Deer' }],
      },
      {
        id: 'summon', title: '3. Tìm Loot Stash và gọi boss',
        paragraphs: ['Loot Stash xuất hiện trong rừng lá rộng hoặc Mosaic đầu mùa đông, có thể ở vị trí khác năm trước. Dùng Deer Antler lên túi sẽ làm sừng vỡ và gọi Klaus: đó là bước đúng, không phải mất vật phẩm do lỗi.'],
        steps: ['Tìm túi trước, chọn bãi trống cạnh đó rồi mới kích hoạt. Dọn vật cản đủ để né vòng, không cần kéo boss xuyên bản đồ.', 'Mặc giáp và sưởi ấm trước khi dùng sừng. Khi boss hiện ra, xác định ngay Klaus, hươu đỏ và hươu xanh.', 'Chọn mục tiêu cẩn thận. Tránh giữ lệnh tấn công vô thức giữa một cụm sinh vật nếu chưa chắc nhân vật sẽ đánh ai.'],
        sources: [{ page: 'Loot_Stash' }, { page: 'Deer_Antler' }],
      },
      {
        id: 'phase-one', title: '4. Pha một: né quẹt tay và vùng phép',
        paragraphs: ['Klaus có chuỗi quẹt tay; đợi chuỗi kết thúc rồi mới áp sát. Hươu đỏ tạo vùng nóng gây cháy, hươu xanh tạo vùng lạnh đóng băng. Khi thấy phép nhắm xuống đất, rời vị trí đó trước khi tiếp tục đánh.'],
        steps: ['Dụ đòn rồi lùi, quay lại đánh ngắn. Mỗi lần bị trúng là tín hiệu giảm thời gian tham đánh, không phải cố bù sát thương ngay.', 'Đi vòng sang phần đất sạch khi hươu niệm phép. Nhìn vị trí con hươu còn lại để không né phép xong lại đứng sát nó.', 'Khi Krampus xuất hiện, giải quyết áp lực phụ rồi mới quay lại nhịp chính. Giữ đường lùi thông thoáng.', 'Không giết hươu hoặc kéo chúng quá xa Klaus: cả hai việc đều có thể khiến boss cuồng nộ.'],
        sources: [{ page: 'Klaus' }, { page: 'Gem_Deer' }],
      },
      {
        id: 'phase-two', title: '5. Hồi sinh: đọc đòn chồm trước khi phản công',
        paragraphs: ['Lần gục đầu chưa kết thúc trận. Klaus hồi sinh và có thêm đòn chồm cắn bằng miệng bụng. Hãy dùng khoảng chuyển pha để chỉnh vị trí, không đứng cạnh xác chờ nhặt đồ.'],
        steps: ['Hồi máu và đổi giáp nếu có cửa sổ an toàn. Quan sát lại từ đầu vì nhịp ở pha một không còn đủ.', 'Khi thấy chuẩn bị chồm, né khỏi đường lao. Boss còn nối tiếp hai cú quẹt: dụ và né hết chuỗi rồi mới phản công, không lao vào ngay lúc nó vừa đáp.', 'Tiếp tục tránh phép hươu. Ưu tiên chọn phần đất sạch trước rồi mới nghĩ tới khoảng đứng đánh.', 'Nếu phải rút, ưu tiên sống sót nhưng đừng tính đó là cách giữ tiến độ: Klaus có hồi máu ngoài giao tranh và có thể biến mất khi khu vực không còn được tải.'],
        sources: [{ page: 'Klaus' }, { page: 'Gem_Deer' }],
      },
      {
        id: 'open-stash', title: '6. Mở túi và lên lịch lần săn tiếp',
        paragraphs: ['Nhặt Stag Antler sau chiến thắng và dùng lên Loot Stash. Đây mới là chìa mở túi; tên gần giống Deer Antler nhưng công dụng khác. Thường nhận bốn Bundled Supplies, còn Winter’s Feast có cách phát quà riêng.'],
        steps: ['Mở các gói tại nơi an toàn với túi đồ đã dọn chỗ. Giữ Wax Paper trả lại khi mở để phục vụ Bundling Wrap sau này.', 'Phân loại vật phẩm thật sự nhận được trước khi lập kế hoạch chế tạo. Đồ hiếm là phần thưởng ngẫu nhiên, không phải món chắc chắn của mỗi lượt.', 'Ở thế giới bình thường, lên kế hoạch tìm lại túi mùa đông năm sau. Winter’s Feast cho chu kỳ khác, nên kiểm tra sự kiện trước khi tính lịch farm.'],
        sources: [{ page: 'Loot_Stash' }, { page: 'Bundling_Wrap/DST' }],
      },
    ],
    rewards: [{ name: 'Stag Antler', use: 'Chìa đúng để mở Loot Stash sau trận.', page: 'Stag_Antler' }, { name: 'Bundled Supplies', use: 'Các gói thưởng gồm vật phẩm và cơ hội có đồ hiếm.', page: 'Loot_Stash' }, { name: 'Red Gem và Blue Gem', use: 'Nhặt khi Gem Deer sống sót trở lại thành hươu thường.', page: 'Gem_Deer' }],
    mistakes: [
      { question: 'Giết hươu trước có làm trận dễ hơn không?', answer: 'Không. Hươu chết hoặc bị tách quá xa làm Klaus cuồng nộ. Hãy né phép và giữ chúng sống.' },
      { question: 'Tại sao dùng sừng chỉ ra Bone Shards mà không gọi boss?', answer: 'Ngoài việc kiểm tra đúng túi, hãy tìm Stag Antler còn tồn tại trong thế giới. Chiếc chìa này có thể ngăn gọi Klaus mới; sử dụng nó cho Loot Stash.' },
      { question: 'Có chắc được Krampus Sack hoặc đúng bản vẽ cần không?', answer: 'Không. Chiến lợi phẩm hiếm phụ thuộc bảng ngẫu nhiên; đừng chuẩn bị tuyến sau dựa trên giả định một lượt sẽ rơi đúng món.' },
    ],
    next: [{ label: 'Lấy Bundling Wrap trực tiếp từ Bee Queen', href: '/bosses/bee-queen' }, { label: 'Chuẩn bị Scaled Furnace từ Dragonfly', href: '/bosses/dragonfly' }],
  },
];
