-- Bảng chỉnh thủ công Dungeon Shop.
-- Chỉ sửa các con số trong file này; không sửa logic màn hình.
-- Tọa độ tương đối so với tâm card; font dùng UIFONT/NUMBERFONT.

local MANUAL_LAYOUT = {
    player_potion = {
        [1] = {
            card = { x = -249, y = 95 },
            icon = { x = 25, y = 30, scale = 0.1 },
            name = { x = 25, y = -10, font = UIFONT, size = 20 },
            desc = { x = 25, y = -35, font = UIFONT, size = 17 },
            price = { x = -10, y = -70, font = NUMBERFONT, size = 20 },
            stock = { x = 58, y = -70, font = NUMBERFONT, size = 20 },
            buy = { x = 25, y = -95, font = UIFONT, size = 20 },
        },
        [2] = {
            card = { x = -111, y = 95 },
            icon = { x = 38, y = 30, scale = 0.1 },
            name = { x = 38, y = -10, font = UIFONT, size = 20 },
            desc = { x = 38, y = -35, font = UIFONT, size = 17 },
            price = { x = 6, y = -70, font = NUMBERFONT, size = 20 },
            stock = { x = 70, y = -70, font = NUMBERFONT, size = 20 },
            buy = { x = 40, y = -95, font = UIFONT, size = 20 },
        },
        [3] = {
            card = { x = 27, y = 95 },
            icon = { x = 50, y = 30, scale = 0.1 },
            name = { x = 50, y = -10, font = UIFONT, size = 20 },
            desc = { x = 50, y = -35, font = UIFONT, size = 17 },
            price = { x = 18, y = -70, font = NUMBERFONT, size = 20 },
            stock = { x = 81, y = -70, font = NUMBERFONT, size = 20 },
            buy = { x = 50, y = -95, font = UIFONT, size = 20 },
        },
        [4] = {
            card = { x = 165, y = 95 },
            icon = { x = 60, y = 30, scale = 0.1 },
            name = { x = 60, y = -10, font = UIFONT, size = 20 },
            desc = { x = 60, y = -35, font = UIFONT, size = 17 },
            price = { x = 30, y = -70, font = NUMBERFONT, size = 20 },
            stock = { x = 87, y = -70, font = NUMBERFONT, size = 20 },
            buy = { x = 60, y = -95, font = UIFONT, size = 20 },
        },
        [5] = {
            card = { x = 303, y = 95 },
            icon = { x = 68, y = 30, scale = 0.1 },
            name = { x = 68, y = -10, font = UIFONT, size = 20 },
            desc = { x = 68, y = -35, font = UIFONT, size = 17 },
            price = { x = 42, y = -70, font = NUMBERFONT, size = 20 },
            stock = { x = 99, y = -70, font = NUMBERFONT, size = 20 },
            buy = { x = 70, y = -95, font = UIFONT, size = 20 },
        },
        [6] = {
            card = { x = -249, y = -150 },
            icon = { x = 25, y = 97, scale = 0.09 },
            name = { x = 25, y = 64, font = UIFONT, size = 20 },
            desc = { x = 25, y = 39, font = UIFONT, size = 17 },
            price = { x = -10, y = 14, font = NUMBERFONT, size = 20 },
            stock = { x = 58, y = 14, font = NUMBERFONT, size = 20 },
            buy = { x = 25, y = -10, font = UIFONT, size = 20 },
        },
        [7] = {
            card = { x = -111, y = -150 },
            icon = { x = 38, y = 97, scale = 0.09 },
            name = { x = 38, y = 64, font = UIFONT, size = 20 },
            desc = { x = 38, y = 39, font = UIFONT, size = 17 },
            price = { x = 6, y = 14, font = NUMBERFONT, size = 20 },
            stock = { x = 70, y = 14, font = NUMBERFONT, size = 20 },
            buy = { x = 40, y = -10, font = UIFONT, size = 20 },
        },
        [8] = {
            card = { x = 27, y = -150 },
            icon = { x = 50, y = 97, scale = 0.09 },
            name = { x = 50, y = 64, font = UIFONT, size = 20 },
            desc = { x = 50, y = 39, font = UIFONT, size = 17 },
            price = { x = 18, y = 14, font = NUMBERFONT, size = 20 },
            stock = { x = 81, y = 14, font = NUMBERFONT, size = 20 },
            buy = { x = 50, y = -10, font = UIFONT, size = 20 },
        },
        [9] = {
            card = { x = 165, y = -150 },
            icon = { x = 60, y = 97, scale = 0.09 },
            name = { x = 60, y = 64, font = UIFONT, size = 20 },
            desc = { x = 60, y = 39, font = UIFONT, size = 17 },
            price = { x = 30, y = 14, font = NUMBERFONT, size = 20 },
            stock = { x = 87, y = 14, font = NUMBERFONT, size = 20 },
            buy = { x = 60, y = -10, font = UIFONT, size = 20 },
        },
        [10] = {
            card = { x = 303, y = -150 },
            icon = { x = 68, y = 97, scale = 0.09 },
            name = { x = 68, y = 64, font = UIFONT, size = 20 },
            desc = { x = 68, y = 39, font = UIFONT, size = 17 },
            price = { x = 42, y = 14, font = NUMBERFONT, size = 20 },
            stock = { x = 99, y = 14, font = NUMBERFONT, size = 20 },
            buy = { x = 70, y = -10, font = UIFONT, size = 20 },
        },
    },
    disciple_potion = {
        [1] = {
            card = { x = -249, y = 95 },
            icon = { x = 25, y = 30, scale = 0.1 },
            name = { x = 25, y = -10, font = UIFONT, size = 20 },
            desc = { x = 25, y = -35, font = UIFONT, size = 17 },
            price = { x = -10, y = -70, font = NUMBERFONT, size = 20 },
            stock = { x = 58, y = -70, font = NUMBERFONT, size = 20 },
            buy = { x = 25, y = -95, font = UIFONT, size = 20 },
        },
        [2] = {
            card = { x = -111, y = 95 },
            icon = { x = 38, y = 30, scale = 0.1 },
            name = { x = 38, y = -10, font = UIFONT, size = 20 },
            desc = { x = 38, y = -35, font = UIFONT, size = 17 },
            price = { x = 6, y = -70, font = NUMBERFONT, size = 20 },
            stock = { x = 70, y = -70, font = NUMBERFONT, size = 20 },
            buy = { x = 40, y = -95, font = UIFONT, size = 20 },
        },
        [3] = {
            card = { x = 27, y = 95 },
            icon = { x = 50, y = 30, scale = 0.1 },
            name = { x = 50, y = -10, font = UIFONT, size = 20 },
            desc = { x = 50, y = -35, font = UIFONT, size = 17 },
            price = { x = 18, y = -70, font = NUMBERFONT, size = 20 },
            stock = { x = 81, y = -70, font = NUMBERFONT, size = 20 },
            buy = { x = 50, y = -95, font = UIFONT, size = 20 },
        },
        [4] = {
            card = { x = 165, y = 95 },
            icon = { x = 60, y = 30, scale = 0.1 },
            name = { x = 60, y = -10, font = UIFONT, size = 20 },
            desc = { x = 60, y = -35, font = UIFONT, size = 17 },
            price = { x = 30, y = -70, font = NUMBERFONT, size = 20 },
            stock = { x = 87, y = -70, font = NUMBERFONT, size = 20 },
            buy = { x = 60, y = -95, font = UIFONT, size = 20 },
        },
        [5] = {
            card = { x = 303, y = 95 },
            icon = { x = 68, y = 30, scale = 0.1 },
            name = { x = 68, y = -10, font = UIFONT, size = 20 },
            desc = { x = 68, y = -35, font = UIFONT, size = 17 },
            price = { x = 42, y = -70, font = NUMBERFONT, size = 20 },
            stock = { x = 99, y = -70, font = NUMBERFONT, size = 20 },
            buy = { x = 70, y = -95, font = UIFONT, size = 20 },
        },
        [6] = {
            card = { x = -249, y = -150 },
            icon = { x = 25, y = 97, scale = 0.09 },
            name = { x = 25, y = 64, font = UIFONT, size = 20 },
            desc = { x = 25, y = 39, font = UIFONT, size = 17 },
            price = { x = -10, y = 14, font = NUMBERFONT, size = 20 },
            stock = { x = 58, y = 14, font = NUMBERFONT, size = 20 },
            buy = { x = 25, y = -10, font = UIFONT, size = 20 },
        },
        [7] = {
            card = { x = -111, y = -150 },
            icon = { x = 38, y = 97, scale = 0.09 },
            name = { x = 38, y = 64, font = UIFONT, size = 20 },
            desc = { x = 38, y = 39, font = UIFONT, size = 17 },
            price = { x = 6, y = 14, font = NUMBERFONT, size = 20 },
            stock = { x = 70, y = 14, font = NUMBERFONT, size = 20 },
            buy = { x = 40, y = -10, font = UIFONT, size = 20 },
        },
        [8] = {
            card = { x = 27, y = -150 },
            icon = { x = 50, y = 97, scale = 0.09 },
            name = { x = 50, y = 64, font = UIFONT, size = 20 },
            desc = { x = 50, y = 39, font = UIFONT, size = 17 },
            price = { x = 18, y = 14, font = NUMBERFONT, size = 20 },
            stock = { x = 81, y = 14, font = NUMBERFONT, size = 20 },
            buy = { x = 50, y = -10, font = UIFONT, size = 20 },
        },
        [9] = {
            card = { x = 165, y = -150 },
            icon = { x = 60, y = 97, scale = 0.09 },
            name = { x = 60, y = 64, font = UIFONT, size = 20 },
            desc = { x = 60, y = 39, font = UIFONT, size = 17 },
            price = { x = 30, y = 14, font = NUMBERFONT, size = 20 },
            stock = { x = 87, y = 14, font = NUMBERFONT, size = 20 },
            buy = { x = 60, y = -10, font = UIFONT, size = 20 },
        },
        [10] = {
            card = { x = 303, y = -150 },
            icon = { x = 68, y = 97, scale = 0.09 },
            name = { x = 68, y = 64, font = UIFONT, size = 20 },
            desc = { x = 68, y = 39, font = UIFONT, size = 17 },
            price = { x = 42, y = 14, font = NUMBERFONT, size = 20 },
            stock = { x = 99, y = 14, font = NUMBERFONT, size = 20 },
            buy = { x = 70, y = -10, font = UIFONT, size = 20 },
        },
    },
    qol = {
        [1] = {
            card = { x = -249, y = 95 },
            icon = { x = 25, y = 30, scale = 0.1 },
            name = { x = 25, y = -10, font = UIFONT, size = 20 },
            desc = { x = 25, y = -35, font = UIFONT, size = 17 },
            price = { x = -10, y = -70, font = NUMBERFONT, size = 20 },
            stock = { x = 58, y = -70, font = NUMBERFONT, size = 20 },
            buy = { x = 25, y = -95, font = UIFONT, size = 20 },
        },
        [2] = {
            card = { x = -111, y = 95 },
            icon = { x = 38, y = 30, scale = 0.1 },
            name = { x = 38, y = -10, font = UIFONT, size = 20 },
            desc = { x = 38, y = -35, font = UIFONT, size = 17 },
            price = { x = 6, y = -70, font = NUMBERFONT, size = 20 },
            stock = { x = 70, y = -70, font = NUMBERFONT, size = 20 },
            buy = { x = 40, y = -95, font = UIFONT, size = 20 },
        },
        [3] = {
            card = { x = 27, y = 95 },
            icon = { x = 50, y = 30, scale = 0.1 },
            name = { x = 50, y = -10, font = UIFONT, size = 20 },
            desc = { x = 50, y = -35, font = UIFONT, size = 17 },
            price = { x = 18, y = -70, font = NUMBERFONT, size = 20 },
            stock = { x = 81, y = -70, font = NUMBERFONT, size = 20 },
            buy = { x = 50, y = -95, font = UIFONT, size = 20 },
        },
        [4] = {
            card = { x = 165, y = 95 },
            icon = { x = 60, y = 30, scale = 0.1 },
            name = { x = 60, y = -10, font = UIFONT, size = 20 },
            desc = { x = 60, y = -35, font = UIFONT, size = 17 },
            price = { x = 30, y = -70, font = NUMBERFONT, size = 20 },
            stock = { x = 87, y = -70, font = NUMBERFONT, size = 20 },
            buy = { x = 60, y = -95, font = UIFONT, size = 20 },
        },
        [5] = {
            card = { x = 303, y = 95 },
            icon = { x = 68, y = 30, scale = 0.1 },
            name = { x = 68, y = -10, font = UIFONT, size = 20 },
            desc = { x = 68, y = -35, font = UIFONT, size = 17 },
            price = { x = 42, y = -70, font = NUMBERFONT, size = 20 },
            stock = { x = 99, y = -70, font = NUMBERFONT, size = 20 },
            buy = { x = 70, y = -95, font = UIFONT, size = 20 },
        },
        [6] = {
            card = { x = -249, y = -150 },
            icon = { x = 25, y = 97, scale = 0.09 },
            name = { x = 25, y = 64, font = UIFONT, size = 20 },
            desc = { x = 25, y = 39, font = UIFONT, size = 17 },
            price = { x = -10, y = 14, font = NUMBERFONT, size = 20 },
            stock = { x = 58, y = 14, font = NUMBERFONT, size = 20 },
            buy = { x = 25, y = -10, font = UIFONT, size = 20 },
        },
        [7] = {
            card = { x = -111, y = -150 },
            icon = { x = 38, y = 97, scale = 0.09 },
            name = { x = 38, y = 64, font = UIFONT, size = 20 },
            desc = { x = 38, y = 39, font = UIFONT, size = 17 },
            price = { x = 6, y = 14, font = NUMBERFONT, size = 20 },
            stock = { x = 70, y = 14, font = NUMBERFONT, size = 20 },
            buy = { x = 40, y = -10, font = UIFONT, size = 20 },
        },
        [8] = {
            card = { x = 27, y = -150 },
            icon = { x = 50, y = 97, scale = 0.09 },
            name = { x = 50, y = 64, font = UIFONT, size = 20 },
            desc = { x = 50, y = 39, font = UIFONT, size = 17 },
            price = { x = 18, y = 14, font = NUMBERFONT, size = 20 },
            stock = { x = 81, y = 14, font = NUMBERFONT, size = 20 },
            buy = { x = 50, y = -10, font = UIFONT, size = 20 },
        },
        [9] = {
            card = { x = 165, y = -150 },
            icon = { x = 60, y = 97, scale = 0.09 },
            name = { x = 60, y = 64, font = UIFONT, size = 20 },
            desc = { x = 60, y = 39, font = UIFONT, size = 17 },
            price = { x = 30, y = 14, font = NUMBERFONT, size = 20 },
            stock = { x = 87, y = 14, font = NUMBERFONT, size = 20 },
            buy = { x = 60, y = -10, font = UIFONT, size = 20 },
        },
        [10] = {
            card = { x = 303, y = -150 },
            icon = { x = 68, y = 97, scale = 0.09 },
            name = { x = 68, y = 64, font = UIFONT, size = 20 },
            desc = { x = 68, y = 39, font = UIFONT, size = 17 },
            price = { x = 42, y = 14, font = NUMBERFONT, size = 20 },
            stock = { x = 99, y = 14, font = NUMBERFONT, size = 20 },
            buy = { x = 70, y = -10, font = UIFONT, size = 20 },
        },
    },
    weapon = {
        [1] = {
            card = { x = -249, y = 95 },
            icon = { x = 25, y = 30, scale = 0.1 },
            name = { x = 25, y = -10, font = UIFONT, size = 20 },
            desc = { x = 25, y = -35, font = UIFONT, size = 17 },
            price = { x = -10, y = -70, font = NUMBERFONT, size = 20 },
            stock = { x = 58, y = -70, font = NUMBERFONT, size = 20 },
            buy = { x = 25, y = -95, font = UIFONT, size = 20 },
        },
        [2] = {
            card = { x = -111, y = 95 },
            icon = { x = 38, y = 30, scale = 0.1 },
            name = { x = 38, y = -10, font = UIFONT, size = 20 },
            desc = { x = 38, y = -35, font = UIFONT, size = 17 },
            price = { x = 6, y = -70, font = NUMBERFONT, size = 20 },
            stock = { x = 70, y = -70, font = NUMBERFONT, size = 20 },
            buy = { x = 40, y = -95, font = UIFONT, size = 20 },
        },
        [3] = {
            card = { x = 27, y = 95 },
            icon = { x = 50, y = 30, scale = 0.1 },
            name = { x = 50, y = -10, font = UIFONT, size = 20 },
            desc = { x = 50, y = -35, font = UIFONT, size = 17 },
            price = { x = 18, y = -70, font = NUMBERFONT, size = 20 },
            stock = { x = 81, y = -70, font = NUMBERFONT, size = 20 },
            buy = { x = 50, y = -95, font = UIFONT, size = 20 },
        },
        [4] = {
            card = { x = 165, y = 95 },
            icon = { x = 60, y = 30, scale = 0.1 },
            name = { x = 60, y = -10, font = UIFONT, size = 20 },
            desc = { x = 60, y = -35, font = UIFONT, size = 17 },
            price = { x = 30, y = -70, font = NUMBERFONT, size = 20 },
            stock = { x = 87, y = -70, font = NUMBERFONT, size = 20 },
            buy = { x = 60, y = -95, font = UIFONT, size = 20 },
        },
        [5] = {
            card = { x = 303, y = 95 },
            icon = { x = 68, y = 30, scale = 0.1 },
            name = { x = 68, y = -10, font = UIFONT, size = 20 },
            desc = { x = 68, y = -35, font = UIFONT, size = 17 },
            price = { x = 42, y = -70, font = NUMBERFONT, size = 20 },
            stock = { x = 99, y = -70, font = NUMBERFONT, size = 20 },
            buy = { x = 70, y = -95, font = UIFONT, size = 20 },
        },
        [6] = {
            card = { x = -249, y = -150 },
            icon = { x = 25, y = 97, scale = 0.09 },
            name = { x = 25, y = 64, font = UIFONT, size = 20 },
            desc = { x = 25, y = 39, font = UIFONT, size = 17 },
            price = { x = -10, y = 14, font = NUMBERFONT, size = 20 },
            stock = { x = 58, y = 14, font = NUMBERFONT, size = 20 },
            buy = { x = 25, y = -10, font = UIFONT, size = 20 },
        },
        [7] = {
            card = { x = -111, y = -150 },
            icon = { x = 38, y = 97, scale = 0.09 },
            name = { x = 38, y = 64, font = UIFONT, size = 20 },
            desc = { x = 38, y = 39, font = UIFONT, size = 17 },
            price = { x = 6, y = 14, font = NUMBERFONT, size = 20 },
            stock = { x = 70, y = 14, font = NUMBERFONT, size = 20 },
            buy = { x = 40, y = -10, font = UIFONT, size = 20 },
        },
        [8] = {
            card = { x = 27, y = -150 },
            icon = { x = 50, y = 97, scale = 0.09 },
            name = { x = 50, y = 64, font = UIFONT, size = 20 },
            desc = { x = 50, y = 39, font = UIFONT, size = 17 },
            price = { x = 18, y = 14, font = NUMBERFONT, size = 20 },
            stock = { x = 81, y = 14, font = NUMBERFONT, size = 20 },
            buy = { x = 50, y = -10, font = UIFONT, size = 20 },
        },
        [9] = {
            card = { x = 165, y = -150 },
            icon = { x = 60, y = 97, scale = 0.09 },
            name = { x = 60, y = 64, font = UIFONT, size = 20 },
            desc = { x = 60, y = 39, font = UIFONT, size = 17 },
            price = { x = 30, y = 14, font = NUMBERFONT, size = 20 },
            stock = { x = 87, y = 14, font = NUMBERFONT, size = 20 },
            buy = { x = 60, y = -10, font = UIFONT, size = 20 },
        },
        [10] = {
            card = { x = 303, y = -150 },
            icon = { x = 68, y = 97, scale = 0.09 },
            name = { x = 68, y = 64, font = UIFONT, size = 20 },
            desc = { x = 68, y = 39, font = UIFONT, size = 17 },
            price = { x = 42, y = 14, font = NUMBERFONT, size = 20 },
            stock = { x = 99, y = 14, font = NUMBERFONT, size = 20 },
            buy = { x = 70, y = -10, font = UIFONT, size = 20 },
        },
    },
    -- HUD chính: chỉ sửa x/y để di chuyển, font/size để chỉnh chữ.
    -- Các tab dùng x/y của tab; font/size/width/height áp dụng cho nút.
    hud = {
        title = { x = 0, y = 217, width = 1050, height = 58, font = TITLEFONT, size = 40, halign = ANCHOR_MIDDLE },
        coins = { x = 250, y = -212, width = 294, height = 42, font = UIFONT, size = 28, halign = ANCHOR_RIGHT },
        cycle = { x = -230, y = 180, width = 320, height = 36, font = UIFONT, size = 25, halign = ANCHOR_LEFT },
        player_potion = { x = -380, y = 142, width = 148, height = 50, font = UIFONT, size = 25 },
        disciple_potion = { x = -380, y = 98, width = 148, height = 50, font = UIFONT, size = 25 },
        qol = { x = -380, y = 55, width = 148, height = 50, font = UIFONT, size = 25 },
        weapon = { x = -380, y = 11, width = 148, height = 50, font = UIFONT, size = 25 },
        notice = { x = -170, y = -212, width = 650, height = 34, font = UIFONT, size = 25, halign = ANCHOR_MIDDLE },
        close = { x = 386, y = 189, width = 89, height = 38, font = UIFONT, size = 25 },
    },
}

return MANUAL_LAYOUT
