-- Run in an isolated DST world after loading TuTienKy.
local function check(value, message) assert(value, "NHATVU: " .. message) end
local umbrella = SpawnPrefab("nhatvuphuonghoa")
check(umbrella ~= nil, "prefab must be registered")
local fuel = umbrella.components.fueled
check(fuel ~= nil, "umbrella has durability")
fuel:DoDelta(-fuel.maxfuel)
check(umbrella:IsValid() and umbrella.components.equippable == nil, "empty umbrella survives but cannot equip")
local stone = SpawnPrefab("ttk_lingshi1")
stone.components.stackable:SetStackSize(3)
check(umbrella.components.trader:AcceptGift(nil, stone), "accept low-grade stone")
check(math.abs(fuel:GetPercent() - .05) < .00001, "one stone restores exactly five percent")
check(stone.components.stackable:StackSize() == 2, "consume one stone from stack")
check(umbrella.components.equippable ~= nil and not umbrella:HasTag("broken"), "recharge restores use")
local wrong = SpawnPrefab("ttk_lingshi2")
check(not umbrella.components.trader:AbleToAccept(wrong), "reject other stone tiers")
fuel:DoDelta(fuel.maxfuel * .94)
check(umbrella.components.trader:AcceptGift(nil, stone), "top up near full")
check(fuel:GetPercent() == 1, "durability caps at full")
check(not umbrella.components.trader:AbleToAccept(stone), "full umbrella must not consume stones")
local player = SpawnPrefab("wilson")
check(player ~= nil, "ordinary character available")
player.components.inventory:GiveItem(umbrella)
player.components.inventory:Equip(umbrella)
check(umbrella.components.equippable:IsEquipped(), "ordinary character can equip")
player.components.moisture:DoDelta(50)
umbrella.components.spellcaster:CastSpell(player, nil, player)
check(player.components.moisture:GetMoisture() == 0, "spell removes wetness")
check(math.abs(fuel:GetPercent() - .75) < .001, "spell costs 25 percent")
check(player:HasTag("moistureimmunity"), "spell grants wetness immunity")
local buff = player:GetDebuff("nhatvuphuonghoa_buff")
check(buff ~= nil and buff.components.timer:GetTimeLeft("dryover") == 240, "buff lasts 240 seconds")
buff.components.debuff:Stop()
check(not player:HasTag("moistureimmunity"), "buff cleanup removes its immunity")
fuel:DoDelta(-fuel.maxfuel)
check(not umbrella.components.equippable and umbrella:HasTag("broken"), "equipped depletion marks broken")
local saved = umbrella:GetSaveRecord()
umbrella:Remove()
umbrella = SpawnSaveRecord(saved)
check(umbrella.components.equippable == nil, "empty save reload stays unequippable")
local refill = SpawnPrefab("ttk_lingshi1")
check(umbrella.components.trader:AcceptGift(nil, refill), "saved empty umbrella recharges")
check(umbrella.components.equippable ~= nil, "saved umbrella becomes usable")
umbrella:DoTaskInTime(0, function()
    check(umbrella.turn_on == true, "recharged ground umbrella enables rain dome")
    umbrella:Remove()
    player:Remove()
    if stone:IsValid() then stone:Remove() end
    wrong:Remove()
    print("NHATVU_TEST_PASS")
end)
