-- Generated from the installed DST scripts.zip by audit_loot_tables.py.
-- Regenerate with .superpowers/te-dan-sol-high/generate_jitan_loot_tables.py.
return {
    ["antlion"] = {
        source = "scripts/prefabs/antlion.lua:37",
        entries = {
            { prefab = "townportal_blueprint", chance = 1 },
            { prefab = "chesspiece_antlion_sketch", chance = 1 },
            { prefab = "antlionhat_blueprint", chance = 1 },
            { prefab = "townportaltalisman", chance = 1 },
            { prefab = "townportaltalisman", chance = 1 },
            { prefab = "townportaltalisman", chance = 1 },
            { prefab = "townportaltalisman", chance = 1 },
            { prefab = "townportaltalisman", chance = 1 },
            { prefab = "townportaltalisman", chance = 1 },
            { prefab = "townportaltalisman", chance = 0.5 },
            { prefab = "townportaltalisman", chance = 0.5 },
            { prefab = "meat", chance = 1 },
            { prefab = "meat", chance = 1 },
            { prefab = "meat", chance = 1 },
            { prefab = "meat", chance = 1 },
            { prefab = "rocks", chance = 1 },
            { prefab = "rocks", chance = 1 },
            { prefab = "rocks", chance = 0.5 },
            { prefab = "rocks", chance = 0.5 },
        },
    },
    ["bearger"] = {
        source = "scripts/prefabs/bearger.lua:76",
        entries = {
            { prefab = "meat", chance = 1 },
            { prefab = "meat", chance = 1 },
            { prefab = "meat", chance = 1 },
            { prefab = "meat", chance = 1 },
            { prefab = "meat", chance = 1 },
            { prefab = "meat", chance = 1 },
            { prefab = "meat", chance = 1 },
            { prefab = "meat", chance = 1 },
            { prefab = "bearger_fur", chance = 1 },
            { prefab = "chesspiece_bearger_sketch", chance = 1 },
        },
    },
    ["mutatedbearger"] = {
        source = "scripts/prefabs/bearger.lua:90",
        entries = {
            { prefab = "spoiled_food", chance = 1 },
            { prefab = "spoiled_food", chance = 1 },
            { prefab = "spoiled_food", chance = 1 },
            { prefab = "spoiled_food", chance = 0.5 },
            { prefab = "purebrilliance", chance = 1 },
            { prefab = "purebrilliance", chance = 0.75 },
            { prefab = "chesspiece_bearger_mutated_sketch", chance = 1 },
        },
    },
    ["beequeen"] = {
        source = "scripts/prefabs/beequeen.lua:24",
        entries = {
            { prefab = "royal_jelly", chance = 1 },
            { prefab = "royal_jelly", chance = 1 },
            { prefab = "royal_jelly", chance = 1 },
            { prefab = "royal_jelly", chance = 1 },
            { prefab = "royal_jelly", chance = 1 },
            { prefab = "royal_jelly", chance = 1 },
            { prefab = "royal_jelly", chance = 0.5 },
            { prefab = "honeycomb", chance = 1 },
            { prefab = "honeycomb", chance = 0.5 },
            { prefab = "honey", chance = 1 },
            { prefab = "honey", chance = 1 },
            { prefab = "honey", chance = 1 },
            { prefab = "honey", chance = 0.5 },
            { prefab = "stinger", chance = 1 },
            { prefab = "hivehat", chance = 1 },
            { prefab = "bundlewrap_blueprint", chance = 1 },
            { prefab = "chesspiece_beequeen_sketch", chance = 1 },
        },
    },
    ["alterguardian_phase1"] = {
        source = "scripts/prefabs/alterguardian_phase1.lua:38",
        entries = {
            { prefab = "moonrocknugget", chance = 1 },
            { prefab = "moonrocknugget", chance = 1 },
            { prefab = "moonrocknugget", chance = 1 },
            { prefab = "moonrocknugget", chance = 1 },
            { prefab = "moonrocknugget", chance = 1 },
            { prefab = "moonrocknugget", chance = 0.66 },
            { prefab = "moonrocknugget", chance = 0.66 },
        },
    },
    ["alterguardian_phase1_lunarrift"] = {
        source = "scripts/prefabs/alterguardian_phase1.lua:49",
        entries = {
            { prefab = "moonrocknugget", chance = 1 },
            { prefab = "moonrocknugget", chance = 1 },
            { prefab = "moonrocknugget", chance = 1 },
            { prefab = "moonrocknugget", chance = 0.66 },
            { prefab = "moonrocknugget", chance = 0.66 },
            { prefab = "moonglass", chance = 1 },
            { prefab = "moonglass", chance = 1 },
            { prefab = "moonglass", chance = 0.66 },
            { prefab = "moonglass", chance = 0.66 },
            { prefab = "moonglass", chance = 0.33 },
            { prefab = "moonglass_charged", chance = 1 },
            { prefab = "moonglass_charged", chance = 1 },
            { prefab = "moonglass_charged", chance = 0.66 },
            { prefab = "moonglass_charged", chance = 0.34 },
            { prefab = "moonglass_charged", chance = 0.34 },
            { prefab = "purebrilliance", chance = 1 },
            { prefab = "purebrilliance", chance = 1 },
        },
    },
    ["alterguardian_phase2"] = {
        source = "scripts/prefabs/alterguardian_phase2.lua:19",
        entries = {
            { prefab = "moonglass", chance = 1 },
            { prefab = "moonglass", chance = 1 },
            { prefab = "moonglass", chance = 1 },
            { prefab = "moonglass", chance = 1 },
            { prefab = "moonglass", chance = 0.66 },
            { prefab = "moonglass", chance = 0.66 },
            { prefab = "moonrocknugget", chance = 1 },
            { prefab = "moonrocknugget", chance = 1 },
            { prefab = "moonrocknugget", chance = 0.66 },
            { prefab = "moonrocknugget", chance = 0.66 },
        },
    },
    ["alterguardian_phase3"] = {
        source = "scripts/prefabs/alterguardian_phase3.lua:27",
        entries = {
            { prefab = "chesspiece_guardianphase3_sketch", chance = 1 },
            { prefab = "alterguardianhatshard", chance = 1 },
            { prefab = "moonglass", chance = 1 },
            { prefab = "moonglass", chance = 1 },
            { prefab = "moonglass", chance = 1 },
            { prefab = "moonglass", chance = 1 },
            { prefab = "moonglass", chance = 1 },
            { prefab = "moonglass", chance = 1 },
            { prefab = "moonglass", chance = 1 },
            { prefab = "moonglass", chance = 1 },
            { prefab = "moonglass", chance = 1 },
            { prefab = "moonglass", chance = 0.66 },
            { prefab = "moonglass", chance = 0.66 },
            { prefab = "moonglass", chance = 0.66 },
            { prefab = "moonglass", chance = 0.66 },
            { prefab = "moonglass", chance = 0.66 },
            { prefab = "moonglass", chance = 0.33 },
            { prefab = "moonglass", chance = 0.33 },
            { prefab = "moonglass", chance = 0.33 },
            { prefab = "moonglass", chance = 0.33 },
            { prefab = "moonglass", chance = 0.33 },
            { prefab = "moonglass_charged", chance = 1 },
            { prefab = "moonglass_charged", chance = 1 },
            { prefab = "moonglass_charged", chance = 1 },
            { prefab = "moonglass_charged", chance = 1 },
            { prefab = "moonglass_charged", chance = 1 },
            { prefab = "moonglass_charged", chance = 1 },
            { prefab = "moonglass_charged", chance = 0.66 },
            { prefab = "moonglass_charged", chance = 0.66 },
            { prefab = "moonglass_charged", chance = 0.66 },
            { prefab = "moonglass_charged", chance = 0.33 },
            { prefab = "moonglass_charged", chance = 0.33 },
            { prefab = "moonglass_charged", chance = 0.33 },
            { prefab = "moonrocknugget", chance = 1 },
            { prefab = "moonrocknugget", chance = 1 },
            { prefab = "moonrocknugget", chance = 1 },
            { prefab = "moonrocknugget", chance = 1 },
            { prefab = "moonrocknugget", chance = 0.66 },
            { prefab = "moonrocknugget", chance = 0.66 },
        },
    },
    ["alterguardian_phase4_lunarrift"] = {
        source = "scripts/prefabs/alterguardian_phase4_lunarrift.lua:46",
        entries = {
            { prefab = "lunar_seed", chance = 1 },
            { prefab = "lunar_seed", chance = 1 },
            { prefab = "lunar_seed", chance = 1 },
            { prefab = "lunar_seed", chance = 1 },
            { prefab = "lunar_seed", chance = 1 },
            { prefab = "purebrilliance", chance = 1 },
            { prefab = "purebrilliance", chance = 1 },
            { prefab = "purebrilliance", chance = 1 },
            { prefab = "purebrilliance", chance = 1 },
            { prefab = "purebrilliance", chance = 1 },
            { prefab = "purebrilliance", chance = 0.7 },
            { prefab = "purebrilliance", chance = 0.3 },
            { prefab = "trinket_6", chance = 1 },
            { prefab = "trinket_6", chance = 1 },
            { prefab = "trinket_6", chance = 0.7 },
            { prefab = "gears", chance = 1 },
            { prefab = "gears", chance = 0.5 },
            { prefab = "chesspiece_wagboss_lunar_sketch", chance = 1 },
        },
    },
    ["crabking"] = {
        source = "scripts/prefabs/crabking.lua:80",
        entries = {
            { prefab = "trident_blueprint", chance = 1 },
            { prefab = "chesspiece_crabking_sketch", chance = 1 },
            { prefab = "boat_bumper_crabking_kit", chance = 1 },
            { prefab = "barnacle", chance = 1 },
            { prefab = "barnacle", chance = 1 },
            { prefab = "barnacle", chance = 0.25 },
            { prefab = "barnacle", chance = 0.25 },
            { prefab = "meat", chance = 1 },
            { prefab = "meat", chance = 1 },
            { prefab = "meat", chance = 1 },
            { prefab = "meat", chance = 1 },
            { prefab = "meat", chance = 1 },
            { prefab = "meat", chance = 0.5 },
            { prefab = "messagebottle", chance = 1 },
            { prefab = "messagebottle", chance = 1 },
            { prefab = "messagebottle", chance = 0.5 },
            { prefab = "messagebottle", chance = 0.25 },
            { prefab = "singingshell_octave3", chance = 1 },
            { prefab = "singingshell_octave3", chance = 0.5 },
            { prefab = "singingshell_octave3", chance = 0.25 },
            { prefab = "singingshell_octave4", chance = 1 },
            { prefab = "singingshell_octave4", chance = 1 },
            { prefab = "singingshell_octave4", chance = 0.5 },
            { prefab = "singingshell_octave4", chance = 0.25 },
            { prefab = "singingshell_octave5", chance = 1 },
            { prefab = "singingshell_octave5", chance = 1 },
            { prefab = "singingshell_octave5", chance = 1 },
            { prefab = "singingshell_octave5", chance = 0.5 },
            { prefab = "singingshell_octave5", chance = 0.25 },
        },
    },
    ["deerclops"] = {
        source = "scripts/prefabs/deerclops.lua:329",
        entries = {
            { prefab = "meat", chance = 1 },
            { prefab = "meat", chance = 1 },
            { prefab = "meat", chance = 1 },
            { prefab = "meat", chance = 1 },
            { prefab = "meat", chance = 1 },
            { prefab = "meat", chance = 1 },
            { prefab = "meat", chance = 1 },
            { prefab = "meat", chance = 1 },
            { prefab = "deerclops_eyeball", chance = 1 },
            { prefab = "chesspiece_deerclops_sketch", chance = 1 },
        },
    },
    ["mutateddeerclops"] = {
        source = "scripts/prefabs/deerclops.lua:343",
        entries = {
            { prefab = "spoiled_food", chance = 1 },
            { prefab = "spoiled_food", chance = 1 },
            { prefab = "spoiled_food", chance = 1 },
            { prefab = "spoiled_food", chance = 0.5 },
            { prefab = "purebrilliance", chance = 1 },
            { prefab = "purebrilliance", chance = 0.75 },
            { prefab = "ice", chance = 1 },
            { prefab = "ice", chance = 0.75 },
            { prefab = "chesspiece_deerclops_mutated_sketch", chance = 1 },
        },
    },
    ["dragonfly"] = {
        source = "scripts/prefabs/dragonfly.lua:38",
        entries = {
            { prefab = "dragon_scales", chance = 1 },
            { prefab = "dragonflyfurnace_blueprint", chance = 1 },
            { prefab = "chesspiece_dragonfly_sketch", chance = 1 },
            { prefab = "lavae_egg", chance = 0.33 },
            { prefab = "meat", chance = 1 },
            { prefab = "meat", chance = 1 },
            { prefab = "meat", chance = 1 },
            { prefab = "meat", chance = 1 },
            { prefab = "meat", chance = 1 },
            { prefab = "meat", chance = 1 },
            { prefab = "goldnugget", chance = 1 },
            { prefab = "goldnugget", chance = 1 },
            { prefab = "goldnugget", chance = 1 },
            { prefab = "goldnugget", chance = 1 },
            { prefab = "goldnugget", chance = 0.5 },
            { prefab = "goldnugget", chance = 0.5 },
            { prefab = "goldnugget", chance = 0.5 },
            { prefab = "goldnugget", chance = 0.5 },
            { prefab = "redgem", chance = 1 },
            { prefab = "bluegem", chance = 1 },
            { prefab = "purplegem", chance = 1 },
            { prefab = "orangegem", chance = 1 },
            { prefab = "yellowgem", chance = 1 },
            { prefab = "greengem", chance = 1 },
            { prefab = "redgem", chance = 1 },
            { prefab = "bluegem", chance = 1 },
            { prefab = "purplegem", chance = 0.5 },
            { prefab = "orangegem", chance = 0.5 },
            { prefab = "yellowgem", chance = 0.5 },
            { prefab = "greengem", chance = 0.5 },
        },
    },
    ["eyeofterror"] = {
        source = "scripts/prefabs/eyeofterror.lua:457",
        entries = {
            { prefab = "chesspiece_eyeofterror_sketch", chance = 1 },
            { prefab = "eyemaskhat", chance = 1 },
            { prefab = "milkywhites", chance = 1 },
            { prefab = "milkywhites", chance = 1 },
            { prefab = "milkywhites", chance = 1 },
            { prefab = "milkywhites", chance = 0.5 },
            { prefab = "milkywhites", chance = 0.5 },
            { prefab = "monstermeat", chance = 1 },
            { prefab = "monstermeat", chance = 1 },
            { prefab = "monstermeat", chance = 0.5 },
            { prefab = "monstermeat", chance = 0.5 },
        },
    },
    ["twinofterror1"] = {
        source = "scripts/prefabs/eyeofterror.lua:541",
        entries = {
            { prefab = "yellowgem", chance = 1 },
            { prefab = "gears", chance = 1 },
            { prefab = "gears", chance = 1 },
            { prefab = "gears", chance = 1 },
            { prefab = "gears", chance = 0.5 },
            { prefab = "gears", chance = 0.5 },
            { prefab = "transistor", chance = 1 },
            { prefab = "transistor", chance = 1 },
            { prefab = "transistor", chance = 0.75 },
            { prefab = "nightmarefuel", chance = 1 },
            { prefab = "nightmarefuel", chance = 1 },
            { prefab = "nightmarefuel", chance = 0.5 },
            { prefab = "nightmarefuel", chance = 0.5 },
            { prefab = "trinket_6", chance = 1 },
            { prefab = "trinket_6", chance = 0.5 },
        },
    },
    ["twinofterror2"] = {
        source = "scripts/prefabs/eyeofterror.lua:611",
        entries = {
            { prefab = "greengem", chance = 1 },
            { prefab = "gears", chance = 1 },
            { prefab = "gears", chance = 1 },
            { prefab = "gears", chance = 1 },
            { prefab = "gears", chance = 0.5 },
            { prefab = "gears", chance = 0.5 },
            { prefab = "transistor", chance = 1 },
            { prefab = "transistor", chance = 1 },
            { prefab = "transistor", chance = 0.75 },
            { prefab = "nightmarefuel", chance = 1 },
            { prefab = "nightmarefuel", chance = 1 },
            { prefab = "nightmarefuel", chance = 0.5 },
            { prefab = "nightmarefuel", chance = 0.5 },
            { prefab = "trinket_6", chance = 1 },
            { prefab = "trinket_6", chance = 0.5 },
        },
    },
    ["lordfruitfly"] = {
        source = "scripts/prefabs/fruitfly.lua:51",
        entries = {
            { prefab = "plantmeat", chance = 1 },
        },
    },
    ["malbatross"] = {
        source = "scripts/prefabs/malbatross.lua:396",
        entries = {
            { prefab = "meat", chance = 1 },
            { prefab = "meat", chance = 1 },
            { prefab = "meat", chance = 1 },
            { prefab = "meat", chance = 1 },
            { prefab = "meat", chance = 1 },
            { prefab = "meat", chance = 1 },
            { prefab = "meat", chance = 1 },
            { prefab = "malbatross_beak", chance = 1 },
            { prefab = "bluegem", chance = 1 },
            { prefab = "bluegem", chance = 1 },
            { prefab = "bluegem", chance = 0.3 },
            { prefab = "yellowgem", chance = 0.05 },
            { prefab = "chesspiece_malbatross_sketch", chance = 1 },
        },
    },
    ["moose"] = {
        source = "scripts/prefabs/moose.lua:26",
        entries = {
            { prefab = "meat", chance = 1 },
            { prefab = "meat", chance = 1 },
            { prefab = "meat", chance = 1 },
            { prefab = "meat", chance = 1 },
            { prefab = "meat", chance = 1 },
            { prefab = "meat", chance = 1 },
            { prefab = "drumstick", chance = 1 },
            { prefab = "drumstick", chance = 1 },
            { prefab = "goose_feather", chance = 1 },
            { prefab = "goose_feather", chance = 1 },
            { prefab = "goose_feather", chance = 1 },
            { prefab = "goose_feather", chance = 0.33 },
            { prefab = "goose_feather", chance = 0.33 },
            { prefab = "chesspiece_moosegoose_sketch", chance = 1 },
        },
    },
    ["daywalker"] = {
        source = "scripts/prefabs/daywalker.lua:29",
        entries = {
            { prefab = "nightmarefuel", chance = 0.5 },
            { prefab = "horrorfuel", chance = 1 },
            { prefab = "horrorfuel", chance = 1 },
            { prefab = "horrorfuel", chance = 1 },
            { prefab = "horrorfuel", chance = 1 },
            { prefab = "horrorfuel", chance = 0.5 },
            { prefab = "armordreadstone_blueprint", chance = 1 },
            { prefab = "dreadstonehat_blueprint", chance = 1 },
            { prefab = "wall_dreadstone_item_blueprint", chance = 1 },
            { prefab = "chesspiece_daywalker_sketch", chance = 1 },
        },
    },
    ["daywalker2"] = {
        source = "scripts/prefabs/daywalker2.lua:46",
        entries = {
            { prefab = "gears", chance = 0.5 },
            { prefab = "wagpunk_bits", chance = 1 },
            { prefab = "wagpunk_bits", chance = 1 },
            { prefab = "wagpunk_bits", chance = 1 },
            { prefab = "wagpunk_bits", chance = 1 },
            { prefab = "wagpunk_bits", chance = 0.5 },
            { prefab = "scrap_monoclehat", chance = 1 },
            { prefab = "chesspiece_daywalker2_sketch", chance = 1 },
        },
    },
    ["shadow_chesspiece"] = {
        source = "scripts/prefabs/shadowchesspieces.lua:70",
        entries = {
            { prefab = "nightmarefuel", chance = 1 },
            { prefab = "nightmarefuel", chance = 0.5 },
        },
    },
    ["sharkboi"] = {
        source = "scripts/prefabs/sharkboi.lua:29",
        entries = {
            { prefab = "bootleg", chance = 1 },
            { prefab = "bootleg", chance = 1 },
            { prefab = "bootleg", chance = 0.5 },
        },
    },
    ["toadstool"] = {
        source = "scripts/prefabs/toadstool.lua:88",
        entries = {
            { prefab = "froglegs", chance = 1 },
            { prefab = "meat", chance = 1 },
            { prefab = "meat", chance = 1 },
            { prefab = "meat", chance = 1 },
            { prefab = "meat", chance = 0.5 },
            { prefab = "meat", chance = 0.25 },
            { prefab = "shroom_skin", chance = 1 },
            { prefab = "chesspiece_toadstool_sketch", chance = 1 },
            { prefab = "red_cap", chance = 1 },
            { prefab = "red_cap", chance = 0.33 },
            { prefab = "red_cap", chance = 0.33 },
            { prefab = "blue_cap", chance = 1 },
            { prefab = "blue_cap", chance = 0.33 },
            { prefab = "blue_cap", chance = 0.33 },
            { prefab = "green_cap", chance = 1 },
            { prefab = "green_cap", chance = 0.33 },
            { prefab = "green_cap", chance = 0.33 },
        },
    },
    ["toadstool_dark"] = {
        source = "scripts/prefabs/toadstool.lua:113",
        entries = {
            { prefab = "froglegs", chance = 1 },
            { prefab = "meat", chance = 1 },
            { prefab = "meat", chance = 1 },
            { prefab = "meat", chance = 1 },
            { prefab = "meat", chance = 0.5 },
            { prefab = "meat", chance = 0.25 },
            { prefab = "shroom_skin", chance = 1 },
            { prefab = "shroom_skin", chance = 1 },
            { prefab = "chesspiece_toadstool_sketch", chance = 1 },
            { prefab = "red_cap", chance = 1 },
            { prefab = "red_cap", chance = 0.33 },
            { prefab = "red_cap", chance = 0.33 },
            { prefab = "blue_cap", chance = 1 },
            { prefab = "blue_cap", chance = 0.33 },
            { prefab = "blue_cap", chance = 0.33 },
            { prefab = "green_cap", chance = 1 },
            { prefab = "green_cap", chance = 0.33 },
            { prefab = "green_cap", chance = 0.33 },
            { prefab = "mushroom_light2_blueprint", chance = 1 },
            { prefab = "sleepbomb_blueprint", chance = 1 },
        },
    },
    ["stalker"] = {
        source = "scripts/prefabs/stalker.lua:81",
        entries = {
            { prefab = "fossil_piece", chance = 1 },
            { prefab = "fossil_piece", chance = 1 },
            { prefab = "fossil_piece", chance = 1 },
            { prefab = "fossil_piece", chance = 1 },
            { prefab = "fossil_piece", chance = 1 },
            { prefab = "fossil_piece", chance = 1 },
            { prefab = "fossil_piece", chance = 1 },
            { prefab = "fossil_piece", chance = 1 },
        },
    },
    ["warg"] = {
        source = "scripts/prefabs/warg.lua:96",
        entries = {
            { prefab = "monstermeat", chance = 1 },
            { prefab = "monstermeat", chance = 1 },
            { prefab = "monstermeat", chance = 1 },
            { prefab = "monstermeat", chance = 1 },
            { prefab = "monstermeat", chance = 0.5 },
            { prefab = "monstermeat", chance = 0.5 },
            { prefab = "houndstooth", chance = 1 },
            { prefab = "houndstooth", chance = 0.66 },
            { prefab = "houndstooth", chance = 0.33 },
        },
    },
    ["claywarg"] = {
        source = "scripts/prefabs/warg.lua:110",
        entries = {
            { prefab = "redpouch", chance = 1 },
            { prefab = "redpouch", chance = 1 },
            { prefab = "redpouch", chance = 1 },
            { prefab = "redpouch", chance = 1 },
            { prefab = "redpouch", chance = 0.5 },
            { prefab = "redpouch", chance = 0.5 },
            { prefab = "houndstooth", chance = 1 },
            { prefab = "houndstooth", chance = 0.66 },
            { prefab = "houndstooth", chance = 0.33 },
        },
    },
    ["gingerbreadwarg"] = {
        source = "scripts/prefabs/warg.lua:124",
        entries = {
            { prefab = "wintersfeastfuel", chance = 1 },
            { prefab = "wintersfeastfuel", chance = 1 },
            { prefab = "wintersfeastfuel", chance = 1 },
            { prefab = "wintersfeastfuel", chance = 1 },
            { prefab = "wintersfeastfuel", chance = 1 },
            { prefab = "wintersfeastfuel", chance = 0.66 },
            { prefab = "wintersfeastfuel", chance = 0.33 },
            { prefab = "crumbs", chance = 1 },
            { prefab = "crumbs", chance = 1 },
            { prefab = "crumbs", chance = 0.5 },
            { prefab = "crumbs", chance = 0.5 },
            { prefab = "houndstooth", chance = 1 },
            { prefab = "houndstooth", chance = 0.66 },
            { prefab = "houndstooth", chance = 0.33 },
        },
    },
    ["mutatedwarg"] = {
        source = "scripts/prefabs/warg.lua:143",
        entries = {
            { prefab = "spoiled_food", chance = 1 },
            { prefab = "spoiled_food", chance = 1 },
            { prefab = "spoiled_food", chance = 0.5 },
            { prefab = "purebrilliance", chance = 1 },
            { prefab = "purebrilliance", chance = 0.75 },
            { prefab = "moonglass", chance = 1 },
            { prefab = "moonglass", chance = 1 },
            { prefab = "moonglass", chance = 1 },
            { prefab = "moonglass", chance = 0.75 },
            { prefab = "moonglass", chance = 0.75 },
            { prefab = "moonglass", chance = 0.25 },
            { prefab = "chesspiece_warg_mutated_sketch", chance = 1 },
        },
    },
    ["wagboss_robot"] = {
        source = "scripts/prefabs/wagboss_robot.lua:25",
        entries = {
            { prefab = "gears", chance = 0.5 },
            { prefab = "transistor", chance = 0.5 },
            { prefab = "wagpunk_bits", chance = 1 },
            { prefab = "wagpunk_bits", chance = 0.5 },
            { prefab = "chesspiece_wagboss_robot_sketch", chance = 1 },
        },
    },
    ["worm_boss"] = {
        source = "scripts/prefabs/worm_boss.lua:28",
        entries = {
            { prefab = "monstermeat", chance = 1 },
            { prefab = "monstermeat", chance = 1 },
            { prefab = "monstermeat", chance = 1 },
            { prefab = "monstermeat", chance = 0.66 },
            { prefab = "monstermeat", chance = 0.66 },
            { prefab = "wormlight", chance = 1 },
            { prefab = "chesspiece_wormboss_sketch", chance = 1 },
        },
    },
    ["vault_pillar_guard"] = {
        source = "scripts/prefabs/vault_pillar_guard.lua:59",
        entries = {
            { prefab = "thulecite", chance = 1 },
            { prefab = "thulecite", chance = 1 },
            { prefab = "thulecite", chance = 0.5 },
            { prefab = "thulecite_pieces", chance = 1 },
            { prefab = "thulecite_pieces", chance = 0.6667 },
            { prefab = "thulecite_pieces", chance = 0.3333 },
            { prefab = "rocks", chance = 1 },
            { prefab = "rocks", chance = 1 },
            { prefab = "rocks", chance = 0.75 },
            { prefab = "rocks", chance = 0.5 },
            { prefab = "moonrocknugget", chance = 1 },
            { prefab = "moonrocknugget", chance = 1 },
            { prefab = "moonrocknugget", chance = 0.5 },
        },
    },
    ["minotaur"] = {
        source = "scripts/prefabs/minotaur.lua:49",
        entries = {
            { prefab = "meat", chance = 1 },
            { prefab = "meat", chance = 1 },
            { prefab = "meat", chance = 1 },
            { prefab = "meat", chance = 1 },
            { prefab = "meat", chance = 1 },
            { prefab = "meat", chance = 1 },
            { prefab = "meat", chance = 1 },
            { prefab = "meat", chance = 1 },
            { prefab = "support_pillar_scaffold_blueprint", chance = 1 },
            { prefab = "minotaurhorn", chance = 1 },
            { prefab = "chesspiece_minotaur_sketch", chance = 1 },
        },
    },
}
