-- Generated by tools/build_alchemy_defs.py; do not edit manually.
local M = {}

M.furnace = {
  prefab = "xd_liandanlu",
  duration = 180,
  ingredients = {
    { prefab="goldnugget", amount=5 },
    { prefab="cutstone", amount=3 },
    { prefab="flint", amount=3 },
    { prefab="ttk_lingshi1", amount=5 },
  },
}

M.by_prefab = {}

M.by_prefab["xd_danyao_jq"] = {
  prefab = "xd_danyao_jq",
  name = "Tụ Khí Hoàn",
  recipe = {
    output_count = 1,
    ingredients = {
      { prefab="spidergland", amount=5 },
      { prefab="stinger", amount=10 },
      { prefab="tallbirdegg", amount=1 },
      { prefab="ttk_lingshi1", amount=10 },
    },
    crafting_note = "Luyện tại Đan Lô.",
  },
  effects = {
    { trigger="consume", text="Sau khi dùng, đặt cảnh giới mục tiêu thành cấp 1 (Tụ Khí); quá trình chuyển cấp hoàn tất sau khoảng 3 giây." },
  },
}

M.by_prefab["xd_danyao_dt"] = {
  prefab = "xd_danyao_dt",
  name = "Đột Phá Đan",
  recipe = {
    output_count = 1,
    ingredients = {
      { prefab="pigskin", amount=3 },
      { prefab="redgem", amount=3 },
      { prefab="ttk_lingshi1", amount=30 },
    },
    crafting_note = "Luyện tại Đan Lô.",
  },
  effects = {
    { trigger="consume", text="Sau khi dùng, đặt cảnh giới mục tiêu thành cấp 2 (Đoán Thể); quá trình chuyển cấp hoàn tất sau khoảng 3 giây." },
  },
}

M.by_prefab["xd_danyao_zj"] = {
  prefab = "xd_danyao_zj",
  name = "Trúc Cơ Đan",
  recipe = {
    output_count = 1,
    ingredients = {
      { prefab="dragon_scales", amount=1 },
      { prefab="houndstooth", amount=10 },
      { prefab="livinglog", amount=3 },
      { prefab="ttk_lingshi2", amount=1 },
    },
    crafting_note = "Luyện tại Đan Lô.",
  },
  effects = {
    { trigger="consume", text="Dùng ở cảnh giới cấp 2 để thực hiện đột phá lên cấp 3 (Trúc Cơ). Runtime xác nhận đây là đan đột phá có điều kiện; không đọc được xác suất thành công từ phần mã đã mã hóa." },
  },
}

M.by_prefab["xd_danyao_xs"] = {
  prefab = "xd_danyao_xs",
  name = "Tẩy Tủy Đan",
  recipe = {
    output_count = 1,
    ingredients = {
      { prefab="lightbulb", amount=10 },
      { prefab="slurtle_shellpieces", amount=3 },
      { prefab="wormlight", amount=3 },
      { prefab="ttk_lingshi1", amount=20 },
    },
    crafting_note = "Luyện tại Đan Lô.",
  },
  effects = {
    { trigger="consume", text="Sau khi dùng, đặt cảnh giới mục tiêu thành cấp 4 (Tẩy Tủy); quá trình chuyển cấp hoàn tất sau khoảng 3 giây." },
  },
}

M.by_prefab["xd_danyao_hj"] = {
  prefab = "xd_danyao_hj",
  name = "Hóa Tinh Đan",
  recipe = {
    output_count = 1,
    ingredients = {
      { prefab="purplegem", amount=3 },
      { prefab="thulecite", amount=3 },
      { prefab="ttk_boss_core_stalke_fuben", amount=3 },
      { prefab="ttk_lingshi1", amount=50 },
    },
    crafting_note = "Luyện tại Đan Lô.",
  },
  effects = {
    { trigger="consume", text="Sau khi dùng, đặt cảnh giới mục tiêu thành cấp 5 (Hóa Tinh); quá trình chuyển cấp hoàn tất sau khoảng 3 giây." },
  },
}

M.by_prefab["xd_danyao_yz"] = {
  prefab = "xd_danyao_yz",
  name = "Ngưng Chân Đan",
  recipe = {
    output_count = 1,
    ingredients = {
      { prefab="manrabbit_tail", amount=5 },
      { prefab="ttk_lingshi2", amount=2 },
      { prefab="ttk_boss_core_qlch", amount=1 },
    },
    crafting_note = "Luyện tại Đan Lô.",
  },
  effects = {
    { trigger="consume", text="Dùng ở cảnh giới cấp 5 để thực hiện đột phá lên cấp 6 (Kim Đan). Runtime xác nhận đây là đan đột phá có điều kiện; không đọc được xác suất thành công từ phần mã đã mã hóa." },
  },
}

M.by_prefab["xd_danyao_sm"] = {
  prefab = "xd_danyao_sm",
  name = "Sơ Mạch Đan",
  recipe = {
    output_count = 1,
    ingredients = {
      { prefab="fig", amount=10 },
      { prefab="royal_jelly", amount=1 },
      { prefab="saltrock", amount=15 },
      { prefab="ttk_lingshi1", amount=30 },
    },
    crafting_note = "Luyện tại Đan Lô.",
  },
  effects = {
    { trigger="consume", text="Sau khi dùng, đặt cảnh giới mục tiêu thành cấp 7 (Sơ Mạch); quá trình chuyển cấp hoàn tất sau khoảng 3 giây." },
  },
}

M.by_prefab["xd_danyao_rl"] = {
  prefab = "xd_danyao_rl",
  name = "Dung Linh Đan",
  recipe = {
    output_count = 1,
    ingredients = {
      { prefab="cookiecuttershell", amount=7 },
      { prefab="gnarwail_horn", amount=1 },
      { prefab="ttk_boss_core_stalke_fuben", amount=1 },
      { prefab="ttk_lingshi2", amount=1 },
    },
    crafting_note = "Luyện tại Đan Lô.",
  },
  effects = {
    { trigger="consume", text="Sau khi dùng, đặt cảnh giới mục tiêu thành cấp 8 (Dung Linh); quá trình chuyển cấp hoàn tất sau khoảng 3 giây." },
  },
}

M.by_prefab["xd_danyao_jy"] = {
  prefab = "xd_danyao_jy",
  name = "Kết Anh Đan",
  recipe = {
    output_count = 1,
    ingredients = {
      { prefab="butter", amount=1 },
      { prefab="shroom_skin", amount=1 },
      { prefab="ttk_boss_core_jfsn", amount=1 },
      { prefab="ttk_lingshi2", amount=3 },
    },
    crafting_note = "Luyện tại Đan Lô.",
  },
  effects = {
    { trigger="consume", text="Dùng ở cảnh giới cấp 8 để thực hiện đột phá lên cấp 9 (Nguyên Anh). Runtime xác nhận đây là đan đột phá có điều kiện; không đọc được xác suất thành công từ phần mã đã mã hóa." },
  },
}

M.by_prefab["xd_danyao_yx"] = {
  prefab = "xd_danyao_yx",
  name = "Uẩn Huyết Đan",
  recipe = {
    output_count = 1,
    ingredients = {
      { prefab="cursed_monkey_token", amount=5 },
      { prefab="rabbitkingspear", amount=1 },
      { prefab="voidcloth", amount=8 },
      { prefab="ttk_lingshi3", amount=1 },
    },
    crafting_note = "Luyện tại Đan Lô.",
  },
  effects = {
    { trigger="consume", text="Sau khi dùng, đặt cảnh giới mục tiêu thành cấp 10 (Uẩn Huyết); quá trình chuyển cấp hoàn tất sau khoảng 3 giây." },
  },
}

M.by_prefab["xd_danyao_ns"] = {
  prefab = "xd_danyao_ns",
  name = "Ngưng Thần Đan",
  recipe = {
    output_count = 1,
    ingredients = {
      { prefab="alterguardianhatshard", amount=1 },
      { prefab="lunarplant_husk", amount=4 },
      { prefab="milkywhites", amount=3 },
      { prefab="ttk_lingshi3", amount=1 },
    },
    crafting_note = "Luyện tại Đan Lô.",
  },
  effects = {
    { trigger="consume", text="Sau khi dùng, đặt cảnh giới mục tiêu thành cấp 11 (Ngưng Thần); quá trình chuyển cấp hoàn tất sau khoảng 3 giây." },
  },
}

M.by_prefab["xd_danyao_hs"] = {
  prefab = "xd_danyao_hs",
  name = "Hóa Thần Đan",
  recipe = {
    output_count = 1,
    ingredients = {
      { prefab="horrorfuel", amount=8 },
      { prefab="purebrilliance", amount=8 },
      { prefab="ttk_boss_core_baihu", amount=1 },
      { prefab="ttk_lingshi3", amount=1 },
    },
    crafting_note = "Luyện tại Đan Lô.",
  },
  effects = {
    { trigger="consume", text="Dùng ở cảnh giới cấp 11 để thực hiện đột phá lên cấp 12 (Hóa Thần). Runtime xác nhận đây là đan đột phá có điều kiện; không đọc được xác suất thành công từ phần mã đã mã hóa." },
  },
}

M.by_prefab["xd_danyao_hy"] = {
  prefab = "xd_danyao_hy",
  name = "Hồi Nguyên Đan",
  recipe = {
    output_count = 1,
    ingredients = {
      { prefab="ttk_lingshi3", amount=1 },
      { prefab="ttk_pog_tail", amount=3 },
      { prefab="ttk_boss_core_deerclops_ziyun", amount=2 },
      { prefab="ttk_spider_leg", amount=1 },
    },
    crafting_note = "Luyện tại Đan Lô.",
  },
  effects = {
    { trigger="consume", text="Sau khi dùng, đặt cảnh giới mục tiêu thành cấp 13 (Hồi Nguyên); quá trình chuyển cấp hoàn tất sau khoảng 3 giây." },
  },
}

M.by_prefab["xd_danyao_hl"] = {
  prefab = "xd_danyao_hl",
  name = "Hợp Linh Đan",
  recipe = {
    output_count = 1,
    ingredients = {
      { prefab="shadowheart", amount=1 },
      { prefab="ttk_lingshi3", amount=1 },
      { prefab="ttk_boss_core_stalke_fuben", amount=1 },
      { prefab="ttk_boss_core_deerclops_ziyun", amount=1 },
    },
    crafting_note = "Luyện tại Đan Lô.",
  },
  effects = {
    { trigger="consume", text="Sau khi dùng, đặt cảnh giới mục tiêu thành cấp 14 (Hợp Linh); quá trình chuyển cấp hoàn tất sau khoảng 3 giây." },
  },
}

M.by_prefab["xd_danyao_kx"] = {
  prefab = "xd_danyao_kx",
  name = "Khuy Hư Đan",
  recipe = {
    output_count = 1,
    ingredients = {
      { prefab="xd_dy_pshsd_1", amount=1 },
      { prefab="xd_dy_xttyd_1", amount=1 },
      { prefab="ttk_lingshi3", amount=1 },
      { prefab="ttk_npxsz", amount=1 },
    },
    crafting_note = "Luyện tại Đan Lô.",
  },
  effects = {
    { trigger="consume", text="Dùng ở cảnh giới cấp 14 để thực hiện đột phá lên cấp 15 (Phản Hư). Runtime xác nhận đây là đan đột phá có điều kiện; không đọc được xác suất thành công từ phần mã đã mã hóa." },
  },
}

M.by_prefab["xd_dy_cyfxd_1"] = {
  prefab = "xd_dy_cyfxd_1",
  name = "Cuồng Ý Phúc Xà Đan",
  recipe = {
    output_count = 1,
    ingredients = {
      { prefab="dragon_scales", amount=4 },
      { prefab="pepper", amount=12 },
      { prefab="ttk_lc_cyh", amount=16 },
      { prefab="ttk_npxsz", amount=2 },
    },
    crafting_note = "Luyện tại Đan Lô trong 180 giây.",
  },
  effects = {
    { trigger="consume", text="Tăng 40% sát thương gây ra trong 2400 giây." },
  },
  effect = { kind = "damage_mult", multiplier = 1.4, duration = 2400 },
}

M.by_prefab["xd_dy_dmhsd_1"] = {
  prefab = "xd_dy_dmhsd_1",
  name = "Đại Mệnh Hồi Sinh Đan",
  recipe = {
    output_count = 1,
    ingredients = {
      { prefab="mandrake", amount=1 },
      { prefab="royal_jelly", amount=12 },
      { prefab="ttk_lc_dms", amount=16 },
      { prefab="ttk_npxsz", amount=2 },
    },
    crafting_note = "Luyện tại Đan Lô trong 180 giây.",
  },
  effects = {
    { trigger="consume", text="Hồi ngay 120 Máu; sau đó hồi thêm 15 Máu mỗi 6 giây trong 2400 giây." },
  },
  effect = { kind = "health_regen", immediate = 120, amount = 15, interval = 6, duration = 2400 },
}

M.by_prefab["xd_dy_lmsqd_1"] = {
  prefab = "xd_dy_lmsqd_1",
  name = "Lôi Mãng Sát Khí Đan",
  recipe = {
    output_count = 1,
    ingredients = {
      { prefab="asparagus", amount=12 },
      { prefab="ttk_lc_lmg", amount=16 },
      { prefab="ttk_npxsz", amount=2 },
      { prefab="ttk_boss_core_qlch", amount=4 },
    },
    crafting_note = "Luyện tại Đan Lô trong 180 giây.",
  },
  effects = {
    { trigger="consume", text="Mỗi đòn đánh gây thêm 180 sát thương lôi trong 2400 giây; kích hoạt ở 100% số đòn trong phép thử runtime." },
  },
  effect = { kind = "lightning_damage", amount = 180, duration = 2400 },
}

M.by_prefab["xd_dy_qxdhd_1"] = {
  prefab = "xd_dy_qxdhd_1",
  name = "Thanh Tâm Đan",
  recipe = {
    output_count = 1,
    ingredients = {
      { prefab="green_cap", amount=12 },
      { prefab="purebrilliance", amount=6 },
      { prefab="ttk_lc_yhh", amount=16 },
      { prefab="ttk_npxsz", amount=2 },
    },
    crafting_note = "Luyện tại Đan Lô trong 180 giây.",
  },
  effects = {
    { trigger="consume", text="hồi khoảng 6.67 Tinh thần/giây trong 2400 giây (số đo runtime thực tế)." },
  },
  effect = { kind = "sanity_regen", amount = 6.666666666666667, duration = 2400 },
}

M.by_prefab["xd_dy_yfsxd_1"] = {
  prefab = "xd_dy_yfsxd_1",
  name = "Ngự Phong Thần Hành Đan",
  recipe = {
    output_count = 1,
    ingredients = {
      { prefab="carrot", amount=12 },
      { prefab="malbatross_feather", amount=32 },
      { prefab="ttk_lc_qfx", amount=16 },
      { prefab="ttk_npxsz", amount=2 },
    },
    crafting_note = "Luyện tại Đan Lô trong 180 giây.",
  },
  effects = {
    { trigger="consume", text="Tăng 25% tốc độ đi bộ và chạy trong 2400 giây." },
  },
  effect = { kind = "speed_mult", multiplier = 1.25, duration = 2400 },
}

M.by_prefab["xd_dy_pshsd_1"] = {
  prefab = "xd_dy_pshsd_1",
  name = "Phòng Sát Hộ Thân Đan",
  recipe = {
    output_count = 1,
    ingredients = {
      { prefab="potato", amount=12 },
      { prefab="ttk_lc_dms", amount=16 },
      { prefab="ttk_boss_core_stalke_fuben", amount=4 },
      { prefab="ttk_npxsz", amount=2 },
    },
    crafting_note = "Luyện tại Đan Lô trong 180 giây.",
  },
  effects = {
    { trigger="consume", text="Giảm 35% sát thương nhận vào trong 2400 giây." },
  },
  effect = { kind = "damage_reduction", multiplier = 0.65, duration = 2400 },
}

M.by_prefab["xd_dy_qjqsd_1"] = {
  prefab = "xd_dy_qjqsd_1",
  name = "Cường Kình Khai Sơn Đan",
  recipe = {
    output_count = 1,
    ingredients = {
      { prefab="corn", amount=12 },
      { prefab="shroom_skin", amount=4 },
      { prefab="ttk_lc_qfx", amount=16 },
      { prefab="ttk_npxsz", amount=2 },
    },
    crafting_note = "Luyện tại Đan Lô trong 180 giây.",
  },
  effects = {
    { trigger="consume", text="Tăng 90% hiệu suất Chặt, Đập và Đào mỏ trong 2400 giây; không tăng tốc Đào đất, Hái hoặc Thu hoạch." },
  },
  effect = { kind = "work_efficiency", multiplier = 1.9, duration = 2400 },
}

M.by_prefab["xd_dy_xynyd_1"] = {
  prefab = "xd_dy_xynyd_1",
  name = "Huyền Nguyên Ninh Dương Đan",
  recipe = {
    output_count = 1,
    ingredients = {
      { prefab="dragonfruit", amount=12 },
      { prefab="ttk_boss_core_jfsn", amount=4 },
      { prefab="ttk_lc_cyh", amount=16 },
      { prefab="ttk_npxsz", amount=2 },
    },
    crafting_note = "Luyện tại Đan Lô trong 180 giây.",
  },
  effects = {
    { trigger="consume", text="Tạo buff chống lạnh trong 2400 giây. Runtime xác nhận thời lượng nhưng phần mã đã mã hóa không để lộ hệ số chống lạnh." },
  },
  effect = { kind = "cold_protection", duration = 2400 },
}

M.by_prefab["xd_dy_hsphd_1"] = {
  prefab = "xd_dy_hsphd_1",
  name = "Hỏa Sát Phích Hàn Đan",
  recipe = {
    output_count = 1,
    ingredients = {
      { prefab="deerclops_eyeball", amount=3 },
      { prefab="watermelon", amount=12 },
      { prefab="ttk_lc_hsc", amount=16 },
      { prefab="ttk_npxsz", amount=2 },
    },
    crafting_note = "Luyện tại Đan Lô trong 180 giây.",
  },
  effects = {
    { trigger="consume", text="Tạo buff chống nóng trong 2400 giây. Runtime xác nhận thời lượng nhưng phần mã đã mã hóa không để lộ hệ số chống nóng." },
  },
  effect = { kind = "heat_protection", duration = 2400 },
}

M.by_prefab["xd_dy_xttyd_1"] = {
  prefab = "xd_dy_xttyd_1",
  name = "Huyết Thực Thiên Ý Đan",
  recipe = {
    output_count = 1,
    ingredients = {
      { prefab="tomato", amount=12 },
      { prefab="ttk_lc_yhh", amount=16 },
      { prefab="ttk_npxsz", amount=2 },
      { prefab="ttk_boss_core_deerclops_ziyun", amount=4 },
    },
    crafting_note = "Luyện tại Đan Lô trong 180 giây.",
  },
  effects = {
    { trigger="consume", text="Hồi Máu bằng 50% sát thương gây ra trong 2400 giây; kích hoạt ở 100% số đòn trong phép thử runtime." },
  },
  effect = { kind = "lifesteal", fraction = 0.5, duration = 2400 },
}

M.by_prefab["xd_danyao_bg"] = {
  prefab = "xd_danyao_bg",
  name = "Bích Cốc Đan",
  recipe = {
    output_count = 1,
    ingredients = {
      { prefab="cutgrass", amount=3 },
      { prefab="honey", amount=3 },
      { prefab="ttk_lingshi1", amount=5 },
    },
    crafting_note = "Luyện tại Đan Lô.",
  },
  effects = {
    { trigger="consume", text="Giảm tốc độ hao Đói còn 20% bình thường (giảm 80%). Runtime không ghi nhận bộ đếm thời gian, nên hiệu ứng được xem là duy trì cho đến khi trạng thái nhân vật bị thay đổi." },
  },
  effect = { kind = "hunger_rate", multiplier = 0.2 },
}

M.cultivation = {}
M.cultivation[1] = M.by_prefab["xd_danyao_jq"]
M.cultivation[2] = M.by_prefab["xd_danyao_dt"]
M.cultivation[3] = M.by_prefab["xd_danyao_zj"]
M.cultivation[4] = M.by_prefab["xd_danyao_xs"]
M.cultivation[5] = M.by_prefab["xd_danyao_hj"]
M.cultivation[6] = M.by_prefab["xd_danyao_yz"]
M.cultivation[7] = M.by_prefab["xd_danyao_sm"]
M.cultivation[8] = M.by_prefab["xd_danyao_rl"]
M.cultivation[9] = M.by_prefab["xd_danyao_jy"]
M.cultivation[10] = M.by_prefab["xd_danyao_yx"]
M.cultivation[11] = M.by_prefab["xd_danyao_ns"]
M.cultivation[12] = M.by_prefab["xd_danyao_hs"]
M.cultivation[13] = M.by_prefab["xd_danyao_hy"]
M.cultivation[14] = M.by_prefab["xd_danyao_hl"]
M.cultivation[15] = M.by_prefab["xd_danyao_kx"]

M.fasting = M.by_prefab["xd_danyao_bg"]

M.buffs = {}
M.buffs["xd_dy_cyfxd_1"] = M.by_prefab["xd_dy_cyfxd_1"]
M.buffs["xd_dy_dmhsd_1"] = M.by_prefab["xd_dy_dmhsd_1"]
M.buffs["xd_dy_lmsqd_1"] = M.by_prefab["xd_dy_lmsqd_1"]
M.buffs["xd_dy_qxdhd_1"] = M.by_prefab["xd_dy_qxdhd_1"]
M.buffs["xd_dy_yfsxd_1"] = M.by_prefab["xd_dy_yfsxd_1"]
M.buffs["xd_dy_pshsd_1"] = M.by_prefab["xd_dy_pshsd_1"]
M.buffs["xd_dy_qjqsd_1"] = M.by_prefab["xd_dy_qjqsd_1"]
M.buffs["xd_dy_xynyd_1"] = M.by_prefab["xd_dy_xynyd_1"]
M.buffs["xd_dy_hsphd_1"] = M.by_prefab["xd_dy_hsphd_1"]
M.buffs["xd_dy_xttyd_1"] = M.by_prefab["xd_dy_xttyd_1"]

function M.Get(prefab) return M.by_prefab[prefab] end
function M.GetCultivationStage(stage) return M.cultivation[stage] end
function M.GetRecipe(prefab) local row=M.Get(prefab); return row and row.recipe or nil end
return M
