local tlbe1 = {
    "spider",
    "birchnutdrake",
    "catcoon",
    "spiderqueen",
    "bat",
    "bee",
    "beefalo",
    "hound",
    "moonhound",
    "rocky",
    "tallbird",
    "icehound",
    "eyeplant",
    "killerbee",
    "merm",
    "mosquito",
    "leif",
    "leif_sparse",
    "waterplant",
    "spider_healer",
    "spider_water",
    "grassgator",
    "bunnyman",
    "rook",
    "rook_nightmare",
    "worm",
    "shadow_rook",
    "buzzard",
    "eyeofterror_mini",
    "lordfruitfly",
    "fruitdragon",
    "spider_hider",
    "spider_spitter",
    "molebat",
    "bishop",
    "bishop_nightmare",
    "knight",
    "knight_nightmare",
    "shadow_knight",
    "shadowthrall_hands",
    "crawlingnightmare",
    "spider_dropper",
    "dropperweb",
    "monkey",
    "archive_centipede",
    "spat",
    "frog",
    "koalefant_winter",
    "mermguard",
    "penguin",
    "shark",
    "gnarwail",
    "walrus",
    "mossling",
    "deer",
    "squid",
    "otter",
    "pigguard",
    "koalefant_summer",
    "pigman",
    "firehound",
    "spider_warrior",
    "warg",
    "lightninggoat",
    "warglet",
    "powder_monkey",
    "prime_mate",
    "krampus",
    "lavae",
    "mutated_penguin",
    "lunarfrog",
    "tentacle",
    "nightmarebeak",
    "slurper",
    "shadow_bishop",
    "spider_moon",
    "gestalt_guard",
    "bird_mutant_spitter",
    "bird_mutant",
    "lunar_grazer",
    "slurtle",
    "snurtle",
    "mushgnome",
    "lunarthrall_plant_vine_end",
    "shadowthrall_wings"
}
local tlbe2 = {
    "stalker_atrium",
    "fused_shadeling",
    "minotaur",
    "antlion",
    "bearger",
    "deerclops",
    "sharkboi",
    "mutatedbearger",
    "beequeen",
    "crabking",
    "toadstool",
    "malbatross",
    "toadstool_dark",
    "dragonfly",
    "daywalker2",
    "daywalker",
    "shadowthrall_horns",
    "klaus",
    "moose",
    "alterguardian_phase1",
    "alterguardian_phase2",
    "alterguardian_phase3",
    "mutateddeerclops",
    "mutatedwarg"
}
local tble3 = {
	stalker_atrium = {[4] = true,},
	antlion = {[2] = true,[3] = true,[4] = true},
	toadstool = {[2] = true,[3] = true,},
	toadstool_dark = {[2] = true,[3] = true,},
	crabking = {[2] = true,[3] = true,[4] = true,},
	fused_shadeling = {[1] = true,[4] = true,[5] = true,},
	shadowthrall_horns = {[1] = true,[4] = true,[5] = true,},
	klaus = {[1] = true,[4] = true,[5] = true,},
	alterguardian_phase1 = {[1] = true,[4] = true,[5] = true,},
	alterguardian_phase2 = {[1] = true,[4] = true,[5] = true,},
	alterguardian_phase3 = {[1] = true,[4] = true,[5] = true,},
    deerclops = {[4] = true},
    bearger = {[4] = true},
    warg = {[4] = true},
    daywalker = {[4] = true},
    daywalker2 = {[4] = true},
    sharkboi = {[4] = true},
    minotaur = {[4] = true},
}
local newtbl1 = {}
local newtbl2 = {}
for _,v in ipairs(tlbe1) do
	newtbl1[v] = true
end
for _,v in ipairs(tlbe2) do
	newtbl2[v] = true
end
return {
	tbl1 = newtbl1,
	tbl2 = newtbl2,
	tbl3 = tble3,
}
