local __bU__G = {
    ["player"] = {
        ["immuneCold"] = {["name"] = "Miễn nhiễm lạnh"},
        ["immuneHot"] = {["name"] = "Miễn nhiễm nóng"},
        ["immuneFreeze"] = {["name"] = "Miễn nhiễm đóng băng"},
        ["immunePoison"] = {["name"] = "Miễn nhiễm độc"},
        ["fireProtection"] = {["name"] = "Kháng lửa"},
        ["poisonProtection"] = {["name"] = "Kháng độc"},
        ["criticalHitEffect"] = {["name"] = "Sát kích"},
        ["criticalHitRate"] = {["name"] = "Bạo kích"},
        ["addComDamage"] = {["name"] = "Sát thương"},
        ["addSplashDamageAOE"] = {["name"] = "Sát thương lan"},
        ["chanceDodgeAttack"] = {["name"] = "Né tránh"},
        ["killUnderThreshold"] = {["name"] = "Kết liễu"},
        ["addComDamagePercent"] = {["name"] = "Công kích"},
        ["addSpeedPercent"] = {["name"] = "Nhanh nhẹn"},
        ["bloodSuck"] = {["name"] = "Hấp huyết"},
        ["atkAddPoisonChance"] = {["name"] = "Hạ độc", ["desc"] = "Tấn công có cơ hội hạ độc mục tiêu"},
        ["bloodOutburst"] = {
            ["name"] = "Cuồng huyết",
            ["desc"] = "máu càng thấp, sát thương tăng càng nhiều (tối đa 50%)"
        },
        ["spiritFade"] = {["name"] = "Điên loạn", ["desc"] = "não càng thấp, sát thương tăng càng nhiều (tối đa 50%)"},
        ["hungerAssault"] = {["name"] = "Ma đói", ["desc"] = "càng đói, sát thương tăng càng nhiều (tối đa 50%)"},
        ["atkChanceAddFreeze"] = {["name"] = "Đóng băng", ["desc"] = "Tấn công có cơ hội đóng băng mục tiêu"},
        ["addSuppressAddHealth"] = {["name"] = "Giảm Hồi Máu", ["desc"] = "Tấn công có cơ hội giảm hiệu ứng hồi máu"},
        ["healthSuppressNum"] = {["name"] = "Giảm Hồi Máu", ["desc"] = "Giảm hiệu quả hồi máu"},
        ["addFollowDamage"] = {["name"] = "Trợ sát", ["desc"] = "Tăng sát thương quái đi theo"},
        ["addFollowReduceDamage"] = {["name"] = "Trợ giáp", ["desc"] = "Giảm sát thương quái đi theo nhận vào"},
        ["addFollowCritical"] = {["name"] = "Trợ kích", ["desc"] = "Tăng chí mạng quái đi theo"},
        ["moreDamage30To150"] = {["name"] = "Bạo Phát I", ["desc"] = "30% gây x1.5 sát thương"},
        ["moreDamage20To200"] = {["name"] = "Bạo Phát II", ["desc"] = "20% gây x2 sát thương"},
        ["moreDamage10To300"] = {["name"] = "Bạo Phát III", ["desc"] = "10% gây x3 sát thương"},
        ["moreDamage8To500"] = {["name"] = "Bạo Phát IV", ["desc"] = "8% gây x5 sát thương"},
        ["trueDamageNum"] = {["name"] = "Xuyên giáp", ["desc"] = "phần trăm sát thương bỏ qua giáp (tối đa 40%)"},
        ["targetPercentDamage"] = {["name"] = "Trọng thương", ["desc"] = "trừ máu theo %"},
        ["shadowCamp"] = {["name"] = "Trừ ma", ["desc"] = "sinh vật bóng tối ko tấn công"},
        ["moonCamp"] = {["name"] = "Trừ ma", ["desc"] = "sinh vật ảo ảnh ko tấn công"},
        ["immunityMoisture"] = {["name"] = "Miễn nhiễm ướt", ["desc"] = "Ko bị làm ướt"},
        ["workAddSpeed"] = {["name"] = "Tháo vát", ["desc"] = "gấp đôi tốc độ làm việc"},
        ["z_suit_zqrf_hand"] = {["name"] = "", ["desc"] = ""},
        ["z_suit_zqrf_body"] = {["name"] = "", ["desc"] = ""},
        ["z_suit_zqrf_hat"] = {["name"] = "", ["desc"] = ""},
        ["immuneReduceSpeed"] = {["name"] = "Miễn nhiễm làm chậm"},
        ["immuneSuppressNum"] = {["name"] = "Miễn Giảm Hồi Máu"},
        ["add_light"] = {["name"] = "Phổ độ"},
        ["fast_act"] = {["name"] = "Tháo vát"},
        ["work_speed"] = {["name"] = "Tháo vát"},
        ["porter"] = {["name"] = "Miễn nhiễm chậm"},
        ["atk_speed"] = {["name"] = "Liên kích"},
        ["immunitySleep"] = {["name"] = "Miễn nhiễm ru ngủ"},
        ["absorbDamage"] = {["name"] = "Phòng thủ"}
    },
    ["monster"] = {
        ["addMaxHealthNum"] = {["name"] = "Tăng lượng máu tối đa"},
        ["addMaxHealthPercent"] = {["name"] = "Tăng % lượng máu tối đa"},
        ["addComDamageNum"] = {["name"] = "Tăng sát thương"},
        ["addComDamagePercent"] = {["name"] = "Tăng % sát thương"},
        ["reduceAttackedDamage"] = {["name"] = "Giảm sát thương nhận vào"},
        ["atkChanceAddPoison"] = {["name"] = "Tấn công có cơ hội hạ độc mục tiêu"},
        ["hitChanceAddPoison"] = {["name"] = "Bị tấn công có cơ hội hạ độc mục tiêu"},
        ["atkChanceAddFreeze"] = {["name"] = "Tấn công có cơ hội đóng băng mục tiêu"},
        ["hitChanceAddFreeze"] = {["name"] = "Bị tấn công có cơ hội đóng băng mục tiêu"},
        ["atkChanceReduceSpeed"] = {["name"] = "Tấn công có cơ hội làm chậm mục tiêu"},
        ["hitChanceReduceSpeed"] = {["name"] = "Bị tấn công có cơ hội làm chậm mục tiêu"},
        ["atkBlood"] = {["name"] = "Hấp huyết"},
        ["addSpeedPercent"] = {["name"] = "Nhanh nhẹn"},
        ["criticalHitRate"] = {["name"] = "Bạo kích"},
        ["criticalHitEffect"] = {["name"] = "Sát kích"},
        ["attackToAddHealth"] = {["name"] = "Ban phúc"},
        ["reduceDeltaHealthPercent"] = {["name"] = "Giảm lượng máu khôi phục tối đa %%%"},
        ["sunlightStrike"] = {["name"] = "Triều sát", ["desc"] = "Tăng %s ST gây ra buổi sáng"},
        ["afterglowStrike"] = {["name"] = "Vãn sát", ["desc"] = "Tăng %s ST gây ra buổi chiều"},
        ["nightMenace"] = {["name"] = "Dạ sát", ["desc"] = "Tăng %s ST gây ra buổi tối"},
        ["addSuppressAddHealth"] = {["name"] = "Giảm Hồi Máu", ["desc"] = "Tấn công có cơ hội giảm hiệu ứng hồi máu"},
        ["hitSuppressAddHealth"] = {["name"] = "Giảm Hồi Máu", ["desc"] = "Bị tấn công có cơ hội giảm hiệu ứng hồi máu"},
        ["healthSuppressNum"] = {["name"] = "Giảm Hồi Máu", ["desc"] = "Giảm Hồi Máu mục tiêu %s%%"},
        ["iceLaser"] = {["name"] = "Laser", ["desc"] = "Lôi quang tuyệt diệt"},
        ["addTargetDamage"] = {["name"] = "Sợ hãi", ["desc"] = "giảm tinh thần mục tiêu trong 30s"},
        ["immuneFreeze"] = {["name"] = "Kháng băng", ["desc"] = "Kháng đóng băng"},
        ["replaceDamageChance"] = {["name"] = "Kiên cố", ["desc"] = "Có cơ hội miễn nhiễm sát thương nhận vào"},
        ["hitAddMoisture"] = {["name"] = "Ẩm ướt", ["desc"] = "Tấn công gây ướt mục tiêu"},
        ["addColdBuffValue"] = {["name"] = "Làm lạnh", ["desc"] = "Tấn công có cơ hội giảm nhiệt mục tiêu"},
        ["addHotBuffValue"] = {["name"] = "Làm nóng", ["desc"] = "Tấn công có cơ hội tăng nhiệt mục tiêu"},
        ["reduceNightDamage"] = {["name"] = "Dạ thủ", ["desc"] = "Giảm sát thương nhận vào buổi tối"},
        ["reduceSunlightDamage"] = {["name"] = "Triều thủ", ["desc"] = "Giảm sát thương nhận vào buổi sáng"},
        ["reduceAfterglowDamage"] = {["name"] = "Vãn thủ", ["desc"] = "Giảm sát thương nhận vào buổi chiều"},
        ["atkAddArmorReduceBuff"] = {["name"] = "Phá giáp", ["desc"] = "Tấn công có cơ hội phá giáp mục tiêu"},
        ["reducePercentDamage"] = {["name"] = "Phòng thủ", ["desc"] = "Giảm % sát thương nhận vào"},
        ["immuneTearing"] = {["name"] = "Kháng trọng thương", ["desc"] = "Kháng trừ máu theo %"},
        ["immuneTrue"] = {["name"] = "Kháng xuyên giáp", ["desc"] = "Kháng trừ thẳng máu"}
    }
}
return __bU__G
