local __bU__G = {
    ["player"] = {
        ["immuneCold"] = {["name"] = "Miễn nhiễm lạnh"},
        ["immuneHot"] = {["name"] = "Miễn nhiễm nóng"},
        ["immuneFreeze"] = {["name"] = "Miễn nhiễm đóng băng"},
        ["immunePoison"] = {["name"] = "Miễn nhiễm độc"},
        ["immuneBramble"] = {["name"] = "Miễn nhiễm phản đòn"},
        ["fireProtection"] = {["name"] = "Kháng lửa"},
        ["poisonProtection"] = {["name"] = "Kháng độc"},
        ["sanReplaceDamageChance"] = {["name"] = "Hấp thụ", ["desc"] = "Có cơ hội trừ ST vào não (tối đa 80)"},
        ["criticalHitEffect"] = {["name"] = "Sát kích"},
        ["criticalHitRate"] = {["name"] = "Bạo kích"},
        ["addComDamage"] = {["name"] = "Sát thương"},
        ["addSplashDamageAOE"] = {["name"] = "Sát thương lan"},
        ["chanceDodgeAttack"] = {["name"] = "Né tránh"},
        ["killUnderThreshold"] = {["name"] = "Kết liễu"},
        ["addComDamagePercent"] = {["name"] = "Công kích"},
        ["addSpeedPercent"] = {["name"] = "Nhanh nhẹn"},
        ["reduceAttackedDamage"] = {["name"] = "Phòng thủ"},
        ["bloodSuck"] = {["name"] = "Hấp huyết"},
        ["restoreSpirit"] = {["name"] = "Hồi não"},
        ["reflexiveInjury"] = {["name"] = "Phản đòn"},
        ["reflexiveInjuryByPercent"] = {["name"] = "Phản % ST"},
        ["reduceBrambleDamage"] = {["name"] = "Giảm phản đòn"},
        ["atkAddPoisonChance"] = {["name"] = "Hạ độc", ["desc"] = "Tấn công có cơ hội hạ độc mục tiêu"},
        ["nightMenace"] = {["name"] = "Sát ma", ["desc"] = "Tấn công vào sinh vật bóng tối tăng %s ST"},
        ["sunlightStrike"] = {["name"] = "ST sáng", ["desc"] = "+%s ST vào buổi sáng"},
        ["afterglowStrike"] = {["name"] = "ST chiều", ["desc"] = "+%s ST vào buổi chiều"},
        ["soakStrike"] = {["name"] = "ST ướt", ["desc"] = "+%s ST gây ra do ẩm ướt"},
        ["bloodOutburst"] = {
            ["name"] = "Cuồng huyết",
            ["desc"] = "máu càng thấp, sát thương tăng càng nhiều (tối đa 50%)"
        },
        ["spiritFade"] = {["name"] = "Điên loạn", ["desc"] = "não càng thấp, sát thương tăng càng nhiều (tối đa 50%)"},
        ["hungerAssault"] = {["name"] = "Ma đói", ["desc"] = "càng đói, sát thương tăng càng nhiều (tối đa 50%)"},
        ["addHitPigDamage"] = {["name"] = "Trư sát", ["desc"] = "tăng ST gây lên heo"},
        ["addHitFishDamage"] = {["name"] = "Ngư sát", ["desc"] = "tăng ST gây lên cá"},
        ["addHitMonkeyDamage"] = {["name"] = "Hầu sát", ["desc"] = "tăng ST gây lên khỉ"},
        ["addHitGearDamage"] = {["name"] = "Máy sát", ["desc"] = "tăng ST gây lên quái đồng hồ"},
        ["addHitSpiderDamage"] = {["name"] = "Nhện sát", ["desc"] = "tăng ST gây lên nhện"},
        ["addHitDogDamage"] = {["name"] = "Lang sát", ["desc"] = "tăng ST gây lên sói"},
        ["addHitFrogDamage"] = {["name"] = "Oa sát", ["desc"] = "tăng ST gây lên ếch"},
        ["addHitInsectDamage"] = {["name"] = "Trùng sát", ["desc"] = "tăng ST gây lên côn trùng"},
        ["addHitShadowDamage"] = {["name"] = "Ma sát", ["desc"] = "tăng ST gây lên sinh vật bóng tối"},
        ["addHitBossDamage"] = {["name"] = "Thần sát", ["desc"] = "tăng ST gây lên quái trùm"},
        ["addHitPlantDamage"] = {["name"] = "Thực sát", ["desc"] = "tăng ST gây lên thực vật"},
        ["attackToAddHealth"] = {["name"] = "Ban phúc", ["desc"] = "Có cơ hội phục hồi máu khi tấn công"},
        ["sanityReplaceDamage"] = {["name"] = "Hấp thụ", ["desc"] = "Có cơ hội trừ ST vào não"},
        ["atkChanceAddPoison"] = {["name"] = "Hạ độc", ["desc"] = "Tấn công có cơ hội hạ độc mục tiêu (-1máu/3s/480s)"},
        ["hitChanceAddPoison"] = {
            ["name"] = "Giáp độc",
            ["desc"] = "Bị tấn công có cơ hội hạ độc mục tiêu (-1máu/3s/480s)"
        },
        ["atkChanceAddFreeze"] = {["name"] = "Đóng băng", ["desc"] = "Tấn công có cơ hội đóng băng mục tiêu"},
        ["hitChanceAddFreeze"] = {["name"] = "Giáp băng", ["desc"] = "Bị tấn công có cơ hội đóng băng mục tiêu"},
        ["addSuppressAddHealth"] = {["name"] = "Thiêu đốt", ["desc"] = "Tấn công có cơ hội giảm hiệu ứng hồi máu"},
        ["hitSuppressAddHealth"] = {["name"] = "Giáp đốt", ["desc"] = "Bị tấn công có cơ hội giảm hiệu ứng hồi máu"},
        ["healthSuppressNum"] = {["name"] = "Trừng phạt", ["desc"] = "???"},
        ["addFollowDamage"] = {["name"] = "Trợ sát", ["desc"] = "Tăng sát thương quái đi theo"},
        ["addFollowReduceDamage"] = {["name"] = "Trợ giáp", ["desc"] = "Giảm sát thương quái đi theo nhận vào"},
        ["addFollowCritical"] = {["name"] = "Trợ kích", ["desc"] = "Tăng chí mạng quái đi theo"},
        ["moreDamage20To200"] = {["name"] = "Chí mạng x2", ["desc"] = "x2 sát thương"},
        ["moreDamage10To300"] = {["name"] = "Chí mạng x3", ["desc"] = "x3 sát thương"},
        ["moreDamage8To500"] = {["name"] = "Chí mạng x5", ["desc"] = "x5 sát thương"},
        ["trueDamageNum"] = {["name"] = "Xuyên giáp", ["desc"] = "sát thương xuyên giáp"},
        ["targetPercentDamage"] = {["name"] = "Trọng thương", ["desc"] = "trừ máu theo %"},
        ["shadowCamp"] = {["name"] = "Trừ ma", ["desc"] = "sinh vật bóng tối ko tấn công"},
        ["moonCamp"] = {["name"] = "Trừ ma", ["desc"] = "sinh vật ảo ảnh ko tấn công"},
        ["immunityMoisture"] = {["name"] = "Miễn nhiễm ướt", ["desc"] = "Ko bị làm ướt"},
        ["workAddSpeed"] = {["name"] = "Tháo vát", ["desc"] = "gấp đôi tốc độ làm việc"},
        ["z_suit_yhby_hand"] = {["name"] = "Holy light blessing (hand)", ["desc"] = "Holy light blessing (hand)"},
        ["z_suit_yhby_body"] = {
            ["name"] = "Holy light blessing (clothing)",
            ["desc"] = "Holy light blessing (clothing)"
        },
        ["z_suit_yhby_hat"] = {["name"] = "Holy light blessing (head)", ["desc"] = "Holy light blessing (head)"},
        ["z_suit_bhtg_hand"] = {["name"] = "", ["desc"] = ""},
        ["z_suit_bhtg_body"] = {["name"] = "", ["desc"] = ""},
        ["z_suit_bhtg_hat"] = {["name"] = "", ["desc"] = ""},
        ["z_suit_zqrf_hand"] = {["name"] = "", ["desc"] = ""},
        ["z_suit_zqrf_body"] = {["name"] = "", ["desc"] = ""},
        ["z_suit_zqrf_hat"] = {["name"] = "", ["desc"] = ""},
        ["z_suit_fyyy_hand"] = {["name"] = "Feiyun yiying (hand)", ["desc"] = "Feiyun yiying (hand)"},
        ["z_suit_fyyy_body"] = {["name"] = "Feiyun yiying (clothing)", ["desc"] = "Feiyun yiying (clothing)"},
        ["z_suit_fyyy_hat"] = {["name"] = "Feiyun yiying (head)", ["desc"] = "Feiyun yiying (head)"},
        ["immuneReduceSpeed"] = {["name"] = "Miễn nhiễm làm chậm"},
        ["immuneSuppressNum"] = {["name"] = "Miễn nhiễm thiêu đốt"},
        ["atkSpeedatkSpeed"] = {["name"] = "Liên kích"},
        ["add_light"] = {["name"] = "Phổ độ"},
        ["fast_act"] = {["name"] = "Tháo vát"},
        ["work_speed"] = {["name"] = "Tháo vát"},
        ["porter"] = {["name"] = "Miễn nhiễm chậm"},
        ["atk_speed"] = {["name"] = "Liên kích"},
        ["immunitySleep"] = {["name"] = "Miễn nhiễm ru ngủ"},
        ["absorbDamage"] = {["name"] = "Phòng thủ"}
    },
    ["monster"] = {
        ["addMaxHealthNum"] = {["name"] = "Tăng lượng máu tối đa"},
        ["addMaxHealthPercent"] = {["name"] = "Tăng % lượng máu tối đa"},
        ["addComDamageNum"] = {["name"] = "Tăng sát thương"},
        ["addComDamagePercent"] = {["name"] = "Tăng % sát thương"},
        ["reduceAttackedDamage"] = {["name"] = "Giảm sát thương nhận vào"},
        ["reboundDamageNum"] = {["name"] = "Phản đòn"},
        ["reboundDamagePercent"] = {["name"] = "Phản % sát thương"},
        ["atkChanceAddPoison"] = {["name"] = "Tấn công có cơ hội hạ độc mục tiêu"},
        ["hitChanceAddPoison"] = {["name"] = "Bị tấn công có cơ hội hạ độc mục tiêu"},
        ["atkChanceAddFreeze"] = {["name"] = "Tấn công có cơ hội đóng băng mục tiêu"},
        ["hitChanceAddFreeze"] = {["name"] = "Bị tấn công có cơ hội đóng băng mục tiêu"},
        ["atkChanceReduceSpeed"] = {["name"] = "Tấn công có cơ hội làm chậm mục tiêu"},
        ["hitChanceReduceSpeed"] = {["name"] = "Bị tấn công có cơ hội làm chậm mục tiêu"},
        ["atkBlood"] = {["name"] = "Hấp huyết"},
        ["addSpeedPercent"] = {["name"] = "Nhanh nhẹn"},
        ["criticalHitRate"] = {["name"] = "Bạo kích"},
        ["criticalHitEffect"] = {["name"] = "Sát kích"},
        ["attackToAddHealth"] = {["name"] = "Ban phúc"},
        ["reduceDeltaHealthPercent"] = {["name"] = "Giảm lượng máu khôi phục tối đa %%%"},
        ["sunlightStrike"] = {["name"] = "Triều sát", ["desc"] = "Tăng %s ST gây ra buổi sáng"},
        ["afterglowStrike"] = {["name"] = "Vãn sát", ["desc"] = "Tăng %s ST gây ra buổi chiều"},
        ["nightMenace"] = {["name"] = "Dạ sát", ["desc"] = "Tăng %s ST gây ra buổi tối"},
        ["addSuppressAddHealth"] = {["name"] = "Thiêu đốt", ["desc"] = "Tấn công có cơ hội giảm hiệu ứng hồi máu"},
        ["hitSuppressAddHealth"] = {["name"] = "Trừng phạt", ["desc"] = "Bị tấn công có cơ hội giảm hiệu ứng hồi máu"},
        ["healthSuppressNum"] = {["name"] = "Thiêu đốt", ["desc"] = "Thiêu đốt mục tiêu %s %%%"},
        ["iceLaser"] = {["name"] = "Laser", ["desc"] = "Lôi quang tuyệt diệt"},
        ["addTargetDamage"] = {["name"] = "Sợ hãi", ["desc"] = "giảm tinh thần mục tiêu trong 30s"},
        ["immuneFreeze"] = {["name"] = "Kháng băng", ["desc"] = "Kháng đóng băng"},
        ["replaceDamageChance"] = {["name"] = "Kiên cố", ["desc"] = "Có cơ hội miễn nhiễm sát thương nhận vào"},
        ["hitAddMoisture"] = {["name"] = "Ẩm ướt", ["desc"] = "Tấn công gây ướt mục tiêu"},
        ["addColdBuffValue"] = {["name"] = "Làm lạnh", ["desc"] = "Tấn công có cơ hội giảm nhiệt mục tiêu"},
        ["addHotBuffValue"] = {["name"] = "Làm nóng", ["desc"] = "Tấn công có cơ hội tăng nhiệt mục tiêu"},
        ["reduceNightDamage"] = {["name"] = "Dạ thủ", ["desc"] = "Giảm sát thương nhận vào buổi tối"},
        ["reduceSunlightDamage"] = {["name"] = "Triều thủ", ["desc"] = "Giảm sát thương nhận vào buổi sáng"},
        ["reduceAfterglowDamage"] = {["name"] = "Vãn thủ", ["desc"] = "Giảm sát thương nhận vào buổi chiều"},
        ["atkAddArmorReduceBuff"] = {["name"] = "Phá giáp", ["desc"] = "Tấn công có cơ hội phá giáp mục tiêu"},
        ["reducePercentDamage"] = {["name"] = "Phòng thủ", ["desc"] = "Giảm % sát thương nhận vào"},
        ["immuneTearing"] = {["name"] = "Kháng trọng thương", ["desc"] = "Kháng trừ máu theo %"},
        ["immuneTrue"] = {["name"] = "Kháng xuyên giáp", ["desc"] = "Kháng trừ thẳng máu"}
    }
}
return __bU__G
