local b__u__G__ = {
    ["equip"] = {
        {["id"] = "spear", ["name"] = "Spear"},
        {["id"] = "hambat", ["name"] = "Hambat"},
        {["id"] = "nightsword", ["name"] = "Night Sword"},
        {["id"] = "ruins_bat", ["name"] = "Thulecite Club"},
        {["id"] = "glasscutter", ["name"] = "Glass Cutter"},
        {["id"] = "nightstick", ["name"] = "Morning Star"},
        {["id"] = "tentaclespike", ["name"] = "Tentacle Spike"},
        {["id"] = "trident", ["name"] = "Trident"},
        {["id"] = "batbat", ["name"] = "Batbat"},
        {["id"] = "spear_wathgrithr", ["name"] = "Battle Spear"},
        {["id"] = "pocketwatch_weapon", ["name"] = "Alarm Clock"},
        {["id"] = "firestaff", ["name"] = "Wand"},
        {["id"] = "whip", ["name"] = "Three -tailed cat whip"},
        {["id"] = "telestaff", ["name"] = "Transmitted wand"},
        {["id"] = "opalstaff", ["name"] = "Call the moon"},
        {["id"] = "icestaff", ["name"] = "Ice wand"},
        {["id"] = "cane", ["name"] = "Walking cane"},
        {["id"] = "orangestaff", ["name"] = "Lazy wand"},
        {["id"] = "yellowstaff", ["name"] = "Calling star wand"},
        {["id"] = "pitchfork", ["name"] = "Dried grass fork"},
        {["id"] = "bugnet", ["name"] = "Widow"},
        {["id"] = "axe", ["name"] = "Ax"},
        {["id"] = "farm_hoe", ["name"] = "Gardening"},
        {["id"] = "pickaxe", ["name"] = "Hoe"},
        {["id"] = "hammer", ["name"] = "Hammer"},
        {["id"] = "shovel", ["name"] = "Shovel"},
        {["id"] = "brush", ["name"] = "Brush"},
        {["id"] = "brush", ["name"] = "Brush"},
        {["id"] = "golden_farm_hoe", ["name"] = "Golden gardening"},
        {["id"] = "goldenpitchfork", ["name"] = "Golden dry grass fork"},
        {["id"] = "goldenshovel", ["name"] = "Gold shovel"},
        {["id"] = "reskin_tool", ["name"] = "Cleaning broom"},
        {["id"] = "lighter", ["name"] = "Wiluo's lighter"},
        {["id"] = "lantern", ["name"] = "Lamp"},
        {["id"] = "thurible", ["name"] = "Shadow furnace"},
        {["id"] = "torch", ["name"] = "Torch"},
        {["id"] = "staff_tornado", ["name"] = "Weather vane"},
        {["id"] = "fence_rotator", ["name"] = "Fence"},
        {["id"] = "goldenpickaxe", ["name"] = "Golden crane hoe"},
        {["id"] = "goldenaxe", ["name"] = "Golden ax"},
        {["id"] = "pickaxe_lunarplant", ["name"] = "Bright eggplant crushed"},
        {["id"] = "shovel_lunarplant", ["name"] = "Bright eggplant shovel"},
        {["id"] = "multitool_axe_pickaxe", ["name"] = "Multi -ax pick"},
        {["id"] = "moonglassaxe", ["name"] = "Moonlight glass ax"},
        {["id"] = "voidcloth_scythe", ["name"] = "Shadow harlery"},
        {["id"] = "lucy", ["name"] = "Ax"},
        {["id"] = "voidcloth_umbrella", ["name"] = "Shadow umbrella"},
        {["id"] = "sword_lunarplant", ["name"] = "Bright eggplant sword"},
        {["id"] = "staff_lunarplant", ["name"] = "Bright eggplant wand"},
        {["id"] = "hawaiianshirt", ["name"] = "Shirt"},
        {["id"] = "beargervest", ["name"] = "Bear leather vest"},
        {["id"] = "reflectivevest", ["name"] = "Cool summer"},
        {["id"] = "armorwood", ["name"] = "Wooden armor"},
        {["id"] = "sweatervest", ["name"] = "Cash"},
        {["id"] = "armorruins", ["name"] = "Ore"},
        {["id"] = "armor_bramble", ["name"] = "Thorns shell"},
        {["id"] = "armorgrass", ["name"] = "Grasshopper"},
        {["id"] = "armor_sanity", ["name"] = "Night armor"},
        {["id"] = "armormarble", ["name"] = "Marble"},
        {["id"] = "armorsnurtleshell", ["name"] = "Snail armor"},
        {["id"] = "armordragonfly", ["name"] = "Scales"},
        {["id"] = "armorwagpunk", ["name"] = "W.a.r.b.i.s. armor armor"},
        {["id"] = "armordreadstone", ["name"] = "Despair stone armor"},
        {["id"] = "raincoat", ["name"] = "Raincoat"},
        {["id"] = "trunkvest_winter", ["name"] = "Soft vest"},
        {["id"] = "trunkvest_summer", ["name"] = "Ventilation vest"},
        {["id"] = "armorskeleton", ["name"] = "Bone armor"},
        {["id"] = "armorslurper", ["name"] = "Hungry belt"},
        {["id"] = "armor_voidcloth", ["name"] = "Void robe"},
        {["id"] = "hivehat", ["name"] = "Bee crown"},
        {["id"] = "skeletonhat", ["name"] = "Bone helmet"},
        {["id"] = "ruinshat", ["name"] = "Crown crown"},
        {["id"] = "footballhat", ["name"] = "Rugby helmet"},
        {["id"] = "beehat", ["name"] = "Beekeeper"},
        {["id"] = "cookiecutterhat", ["name"] = "Biscuit cutting machine hat"},
        {["id"] = "polly_rogershat", ["name"] = "Polly roger's hat"},
        {["id"] = "bushhat", ["name"] = "Bush"},
        {["id"] = "featherhat", ["name"] = "Feather hat"},
        {["id"] = "antlionhat", ["name"] = "Scrape the leather helmet"},
        {["id"] = "moonstorm_goggleshat", ["name"] = "Star elephant mirror"},
        {["id"] = "blue_mushroomhat", ["name"] = "Blue mushroom hat"},
        {["id"] = "watermelonhat", ["name"] = "Watermelon hat"},
        {["id"] = "deserthat", ["name"] = "Desert goggles"},
        {["id"] = "green_mushroomhat", ["name"] = "Green mushroom hat"},
        {["id"] = "earmuffshat", ["name"] = "Rabbit earmop"},
        {["id"] = "catcoonhat", ["name"] = "Cat hat"},
        {["id"] = "red_mushroomhat", ["name"] = "Red mushroom hat"},
        {["id"] = "tophat", ["name"] = "High cooker"},
        {["id"] = "rainhat", ["name"] = "Raindrop"},
        {["id"] = "kelphat", ["name"] = "Sea flower ring"},
        {["id"] = "wagpunkhat", ["name"] = "W.a.r.b.i.s."},
        {["id"] = "goggleshat", ["name"] = "Fashionable goggles"},
        {["id"] = "flowerhat", ["name"] = "Wreath"},
        {["id"] = "winterhat", ["name"] = "Winter hat"},
        {["id"] = "beefalohat", ["name"] = "Horn"},
        {["id"] = "wathgrithrhat", ["name"] = "Combat helmet"},
        {["id"] = "icehat", ["name"] = "Ice cap"},
        {["id"] = "eyebrellahat", ["name"] = "Eye umbrella"},
        {["id"] = "strawhat", ["name"] = "Straw hat"},
        {["id"] = "batnosehat", ["name"] = "Milk hat"},
        {["id"] = "molehat", ["name"] = "Mouse hat"},
        {["id"] = "voidclothhat", ["name"] = "Void"},
        {["id"] = "dreadstonehat", ["name"] = "Wineon helmet"},
        {["id"] = "eyemaskhat", ["name"] = "Eye mask"},
        {["id"] = "lunarplanthat", ["name"] = "Bright eggplant helmet"},
        {["id"] = "armor_lunarplant", ["name"] = "Bright eggplant armor"},
        {["id"] = "slurtlehat", ["name"] = "Back helmet"},
        {["id"] = "spear_wathgrithr_lightning", ["name"] = "Benlei spear"},
        {["id"] = "spear_wathgrithr_lightning_charged", ["name"] = "Benlei spear"},
        {["id"] = "wathgrithr_improvedhat", ["name"] = "Valkyrie hat"},
        {["id"] = "voidcloth_boomerang", ["name"] = "Shadow back dart"},
        {["id"] = "shadow_battleaxe", ["name"] = "Shadow ax"},
        {["id"] = "rabbitkingspear", ["name"] = "Rabbit King Cudgel"},
        {["id"] = "rabbithat", ["name"] = "Warren Wreath"},
        {["id"] = "machete", ["name"] = "machete"},
        {["id"] = "goldenmachete", ["name"] = "goldenmachete"},
        {["id"] = "obsidianmachete", ["name"] = "obsidianmachete"},
        {["id"] = "shears", ["name"] = "shears"},
        {["id"] = "fishingrod", ["name"] = "fishingrod"},
        {["id"] = "oceanfishingrod", ["name"] = "oceanfishingrod"},
        {["id"] = "oar", ["name"] = "oar"},
        {["id"] = "oar_driftwood", ["name"] = "oar_driftwood"},
        {["id"] = "oar_monkey", ["name"] = "oar_monkey"},
        {["id"] = "malbatross_beak", ["name"] = "malbatross_beak"},
        {["id"] = "walkingstick", ["name"] = "walkingstick"},


        {["id"] = "hh_daogam5", ["name"] = "Hắc Thiên Kiếm"},

        {["id"] = "hh_daogam4", ["name"] = "Trượng Hoả Ngục"},
        {["id"] = "hh_daogam3", ["name"] = "Trượng Ma Vực"},


        {["id"] = "hh_van_nang_trao", ["name"] = "Vạn Năng Trảo"},
        {["id"] = "hh_daogam", ["name"] = "Kiếm Quỷ Vương"},
        {["id"] = "hh_daogam2", ["name"] = "Hắc Ảnh Kiếm"},
        {["id"] = "hh_daogam6", ["name"] = "Tà Thuật Đen - Vũ Khí"}
    },
    ["organism"] = {
        {["id"] = "hh_dungeon_pig", ["name"] = "Dungeon Pig"},
        {["id"] = "hh_dungeon_spider", ["name"] = "Dungeon Spider"},
        {["id"] = "hh_dungeon_firehound", ["name"] = "Dungeon Fire Hound"},
        {["id"] = "hh_dungeon_icehound", ["name"] = "Dungeon Ice Hound"},
        {["id"] = "hh_dungeon_snowhound", ["name"] = "Dungeon Snow Hound"},
        {["id"] = "hh_dungeon_lightninghound", ["name"] = "Dungeon Lightning Hound"},
        {["id"] = "hh_dungeon_horrorhound", ["name"] = "Dungeon Horror Hound"},
        {["id"] = "pigguard", ["name"] = "Pig guard"},
        {["id"] = "pigman", ["name"] = "Pig"},
        {["id"] = "wildbore", ["name"] = "Wild boar"},
        {["id"] = "bunnyman", ["name"] = "Rabbit"},
        {["id"] = "rabbitkingminion_bunnyman", ["name"] = "Shadow rabbit man"},
        {["id"] = "rabbitking_aggressive", ["name"] = "Shadow rabbit king"},
        {["id"] = "merm", ["name"] = "Fisherman"},
        {["id"] = "mermguard", ["name"] = "Mermaid guard"},
        {["id"] = "merm_shadow", ["name"] = "Shadow mim"},
        {["id"] = "mermguard_shadow", ["name"] = "Shadow mim"},
        {["id"] = "merm_lunar", ["name"] = "Moonflake"},
        {["id"] = "mermguard_lunar", ["name"] = "Moonflake"},
        {["id"] = "mermfisher", ["name"] = "Old mermaid"},
        {["id"] = "little_walrus", ["name"] = "Small maritine"},
        {["id"] = "walrus", ["name"] = "Walrus"},
        {["id"] = "knight", ["name"] = "Clockwork"},
        {["id"] = "bishop", ["name"] = "Strip bishop"},
        {["id"] = "rook", ["name"] = "Straight chariot"},
        {["id"] = "knight_nightmare", ["name"] = "Damaged clockwork knight"},
        {["id"] = "bishop_nightmare", ["name"] = "Damaged hair bishop"},
        {["id"] = "rook_nightmare", ["name"] = "Damaged haircut chariot"},
        {["id"] = "knightboat", ["name"] = "Clockwork knight boat"},
        {["id"] = "spider", ["name"] = "Spider"},
        {["id"] = "spider_warrior", ["name"] = "Spider warrior"},
        {["id"] = "spider_hider", ["name"] = "Cave spider"},
        {["id"] = "spider_spitter", ["name"] = "Spider spider"},
        {["id"] = "spider_dropper", ["name"] = "Hangju suspension spider"},
        {["id"] = "spider_moon", ["name"] = "Broken spider (moon)"},
        {["id"] = "spider_water", ["name"] = "Haiji-sea spider"},
        {["id"] = "tropical_spider_warrior", ["name"] = "Poison spider warrior"},
        {["id"] = "hound", ["name"] = "Hound"},
        {["id"] = "firehound", ["name"] = "Red hunting"},
        {["id"] = "icehound", ["name"] = "Blue hound"},
        {["id"] = "mutatedhound", ["name"] = "Horror hunting dog"},
        {["id"] = "crocodog", ["name"] = "Crocodile"},
        {["id"] = "watercrocodog", ["name"] = "Watery dog"},
        {["id"] = "poisoncrocodog", ["name"] = "Crocodile"},
        {["id"] = "frog", ["name"] = "Frog"},
        {["id"] = "lunarfrog", ["name"] = "Eye frog"},
        {["id"] = "catcoon", ["name"] = "Rampant"},
        {["id"] = "bat", ["name"] = "Cave bat"},
        {["id"] = "shark", ["name"] = "Rock great white shark"},
        {["id"] = "gnarwail", ["name"] = "One corner whale"},
        {["id"] = "squid", ["name"] = "Squid"},
        {["id"] = "swordfish", ["name"] = "Swordfish"},
        {["id"] = "solofish", ["name"] = "Dogfish"},
        {["id"] = "jellyfish_planted", ["name"] = "Sailor"},
        {["id"] = "rainbowjellyfish_planted", ["name"] = "Rainbow watermother"},
        {["id"] = "whale_blue", ["name"] = "Blue whale"},
        {["id"] = "whale_white", ["name"] = "White whale"},
        {["id"] = "ballphin", ["name"] = "Dolphin"},
        {["id"] = "stungray", ["name"] = "Sting"},
        {["id"] = "tallbird", ["name"] = "Tall bird"},
        {["id"] = "penguin", ["name"] = "Gull"},
        {["id"] = "mutated_penguin", ["name"] = "Yueyan enterprise"},
        {["id"] = "mutatedbuzzard_gestalt", ["name"] = "Crystal-Crested Buzzard"},
        {["id"] = "babybeefalo", ["name"] = "Little pipplo niu"},
        {["id"] = "beefalo", ["name"] = "Pip lou niu"},
        {["id"] = "ox", ["name"] = "Buffalo"},
        {["id"] = "babyox", ["name"] = "Buffalo"},
        {["id"] = "koalefant_summer", ["name"] = "Kao la"},
        {["id"] = "koalefant_winter", ["name"] = "Kao la"},
        {["id"] = "lightninggoat", ["name"] = "Vodal"},
        {["id"] = "tentacle", ["name"] = "Tentacle"},
        {["id"] = "bee", ["name"] = "Bee"},
        {["id"] = "killerbee", ["name"] = "Murder"},
        {["id"] = "beeguard", ["name"] = "Buzzed bee"},
        {["id"] = "mushgnome", ["name"] = "Mushroom geomorphism"},
        {["id"] = "grassgekko", ["name"] = "Grasshopper"},
        {["id"] = "monkey", ["name"] = "Cave monkey"},
        {["id"] = "prime_mate", ["name"] = "Vice"},
        {["id"] = "powder_monkey", ["name"] = "Gunpowder monkey"},
        {["id"] = "primeape", ["name"] = "Monkey"},
        {["id"] = "slurtle", ["name"] = "Turtle"},
        {["id"] = "snurtle", ["name"] = "Snail turtle"},
        {["id"] = "rocky", ["name"] = "Stones shrimp"},
        {["id"] = "slurper", ["name"] = "Tanker"},
        {["id"] = "worm", ["name"] = "Cave"},
        {["id"] = "krampus", ["name"] = "Kampos"},
        {["id"] = "ghost", ["name"] = "Ghost"},
        {["id"] = "waterplant", ["name"] = "Seaweed"},
        {["id"] = "deer", ["name"] = "Eyeless deer"},
        {["id"] = "deer_red", ["name"] = "Eyeless deer-red"},
        {["id"] = "deer_blue", ["name"] = "Eyeless deer-blue"},
        {["id"] = "mossling", ["name"] = "Elk goose cub"},
        {["id"] = "twister_seal", ["name"] = "Little seal"},
        {["id"] = "sharkitten", ["name"] = "Little tiger shark"},
        {["id"] = "doydoy", ["name"] = "Ferry bird"},
        {["id"] = "doydoybaby", ["name"] = "Baby watanabe"},
        {["id"] = "crab", ["name"] = "Rabbit crab"},
        {["id"] = "flup", ["name"] = "Big -eyed fish"},
        {["id"] = "dragoon", ["name"] = "Dumb dragon"},
        {["id"] = "kraken_tentacle", ["name"] = "Sea demon tentacle"},
        {["id"] = "crabking_mob", ["name"] = "Crab Guard"},
        {["id"] = "crabking_mob_knight", ["name"] = "Crab Knight"},
        {["id"] = "crabking_claw", ["name"] = "Giant pliers"},
        {["id"] = "eyeofterror_mini", ["name"] = "Suspicious peek-little eye pearl"},
        {["id"] = "shadowthrall_hands", ["name"] = "Ink desert-two hands"},
        {["id"] = "shadowthrall_horns", ["name"] = "Ink desert-will eat people"},
        {["id"] = "shadowthrall_wings", ["name"] = "Ink desert-wings"},
        {["id"] = "shadowthrall_mouth", ["name"] = "Ink-snake"},
        {["id"] = "crawlinghorror", ["name"] = "Climbing"},
        {["id"] = "terrorbeak", ["name"] = "Horrible beak"},
        {["id"] = "fused_shadeling", ["name"] = "Melting dark shadow"},
        {["id"] = "swimminghorror", ["name"] = "Shadow in the water"},
        {["id"] = "mosquito", ["name"] = "Mosquito"},
        {["id"] = "mosquito_poison", ["name"] = "Poisonous mosquito"},
        {["id"] = "snake", ["name"] = "Snake"},
        {["id"] = "snake_poison", ["name"] = "Poisonous snake"},
        {["id"] = "warglet", ["name"] = "Youth wolf"},
        {["id"] = "grassgator", ["name"] = "Crocodile"},
        {["id"] = "spat", ["name"] = "Steel sheep"},
        {["id"] = "warg", ["name"] = "Wolf"},
        {["id"] = "lunarthrall_plant", ["name"] = "Shiny eggplant"},
        {["id"] = "klaus", ["name"] = "Claus"},
        {["id"] = "daywalker", ["name"] = "Nightmare pig"},
        {["id"] = "daywalker2", ["name"] = "Nightmare pig"},
        {["id"] = "alterguardian_phase1", ["name"] = "Celestial heroes-"},
        {["id"] = "alterguardian_phase2", ["name"] = "Celestial heroes-"},
        {["id"] = "alterguardian_phase3", ["name"] = "Celestial heroes-"},
        {["id"] = "crabking", ["name"] = "King crab"},
        {["id"] = "eyeofterror", ["name"] = "Eyes of horror-big eye beads"},
        {["id"] = "toadstool", ["name"] = "Poisonous toad"},
        {["id"] = "toadstool_dark", ["name"] = "Tragic to toad"},
        {["id"] = "lordfruitfly", ["name"] = "Fruge king"},
        {["id"] = "beequeen", ["name"] = "Bee king"},
        {["id"] = "mutateddeerclops", ["name"] = "Crystal diller giant deer"},
        {["id"] = "shadow_bishop", ["name"] = "Shadow bishop"},
        {["id"] = "shadow_rook", ["name"] = "Shadow chariot"},
        {["id"] = "shadow_knight", ["name"] = "Shadow knight"},
        {["id"] = "leif", ["name"] = "Tree essence"},
        {["id"] = "leif_sparse", ["name"] = "Tree guard"},
        {["id"] = "twinofterror1", ["name"] = "Laser eye"},
        {["id"] = "twinofterror2", ["name"] = "Magic flame"},
        {["id"] = "mutatedbearger", ["name"] = "Armored bear"},
        {["id"] = "bearger", ["name"] = "Beacon"},
        {["id"] = "deerclops", ["name"] = "One -eyed giant deer"},
        {["id"] = "antlion", ["name"] = "Ant"},
        {["id"] = "spiderqueen", ["name"] = "Spider queen"},
        {["id"] = "minotaur", ["name"] = "Ancient guardian"},
        {["id"] = "stalker_atrium", ["name"] = "Ancient weaving"},
        {["id"] = "stalker_forest", ["name"] = "Green weaving"},
        {["id"] = "malbatross", ["name"] = "Evil spirits"},
        {["id"] = "mutatedwarg", ["name"] = "Wolf"},
        {["id"] = "moose", ["name"] = "Elk goose"},
        {["id"] = "dragonfly", ["name"] = "Dragon fly"},
        {["id"] = "sharkboi", ["name"] = "Big shark"},
        {["id"] = "hh_sharkboi", ["name"] = "Shark"},
        {["id"] = "shadow_leech", ["name"] = "shadow_leech"},
        {["id"] = "ruinsnightmare", ["name"] = "ruinsnightmare"},
        {["id"] = "oceanhorror", ["name"] = "oceanhorror"},
        {["id"] = "fused_shadeling_bomb", ["name"] = "fused_shadeling_bomb"},
        {["id"] = "shadowtentacle", ["name"] = "shadowtentacle"},
        {["id"] = "gelblob", ["name"] = "gelblob"},
        {["id"] = "moonpig", ["name"] = "moonpig"},
        {["id"] = "lavae", ["name"] = "lavae"},
        {["id"] = "myth_nian", ["name"] = "myth_nian"},
        {["id"] = "rhino3_red", ["name"] = "rhino3_red"},
        {["id"] = "rhino3_blue", ["name"] = "rhino3_blue"},
        {["id"] = "rhino3_yellow", ["name"] = "rhino3_yellow"},
        {["id"] = "blackbear", ["name"] = "blackbear"},
        {["id"] = "myth_goldfrog", ["name"] = "myth_goldfrog"},
        {["id"] = "myth_siving_boss", ["name"] = "myth_siving_boss"},
        {["id"] = "siving_foenix", ["name"] = "siving_foenix"},
        {["id"] = "siving_moenix", ["name"] = "siving_moenix"},
        {["id"] = "tigershark", ["name"] = "tigershark"},
        {["id"] = "twister", ["name"] = "twister"},
        {["id"] = "kraken", ["name"] = "kraken"},
        {["id"] = "leif_palm", ["name"] = "Coconut tree essence"},
        {["id"] = "leif_jungle", ["name"] = "Jungle tree essence"},
        {["id"] = "antman2", ["name"] = "Tela-ant man"},
        {["id"] = "adult_flytrap", ["name"] = "adult_flytrap"},
        {["id"] = "spider_monkey", ["name"] = "spider_monkey"},
        {["id"] = "pigbandit", ["name"] = "pigbandit"},
        {["id"] = "antqueen", ["name"] = "antqueen"},
        {["id"] = "ancient_herald", ["name"] = "ancient_herald"},
        {["id"] = "pugalisk", ["name"] = "pugalisk"},
        {["id"] = "ancient_hulk", ["name"] = "ancient_hulk"},
        {["id"] = "mothergoose", ["name"] = "mothergoose"},
        {["id"] = "mock_dragonfly", ["name"] = "mock_dragonfly"},
        {["id"] = "moonmaw_dragonfly", ["name"] = "moonmaw_dragonfly"},
        {["id"] = "hoodedwidow", ["name"] = "hoodedwidow"},
        {["id"] = "medal_beequeenhivegrown", ["name"] = "medal_beequeenhivegrown"},
        {["id"] = "medal_spacetime_devourer", ["name"] = "medal_spacetime_devourer"},
        {["id"] = "medal_rage_krampus", ["name"] = "medal_rage_krampus"},
        {["id"] = "medal_beequeen", ["name"] = "medal_beequeen"},
        {["id"] = "minotau", ["name"] = "minotau"},
        {["id"] = "bird_mutant", ["name"] = "Mutant Bird"},
        {["id"] = "bird_mutant_spitter", ["name"] = "Mutant Spitter Bird"},
        {["id"] = "birchnutdrake", ["name"] = "Birchnut Drake"},
        {["id"] = "lightcrab", ["name"] = "Light Crab"},
        {["id"] = "moonhound", ["name"] = "Moon Hound"},
        {["id"] = "clayhound", ["name"] = "Clay Hound"},
        {["id"] = "hedgehound", ["name"] = "Hedge Hound"},
        {["id"] = "fruitdragon", ["name"] = "Fruit Dragon"},
        {["id"] = "claywarg", ["name"] = "Clay Warg"},
        {["id"] = "gingerbreadwarg", ["name"] = "Gingerbread Warg"},
        {["id"] = "itemmimic_revealed", ["name"] = "Revealed Item Mimic"},
        {["id"] = "chest_mimic_revealed", ["name"] = "Revealed Chest Mimic"},
        {["id"] = "worm_boss", ["name"] = "Worm Boss"},
        {["id"] = "graveguard_ghost", ["name"] = "Graveguard Ghost"},
        {["id"] = "buzzard", ["name"] = "Buzzard"},
        {["id"] = "cookiecutter", ["name"] = "Cookiecutter"},
        {["id"] = "lureplant", ["name"] = "Lureplant"},
        {["id"] = "molebat", ["name"] = "Mole Bat"},
        {["id"] = "spider_healer", ["name"] = "Spider Healer"},
        {["id"] = "tentacle_pillar", ["name"] = "Tentacle Pillar"},
        {["id"] = "alterguardian_phase4_lunarrift", ["name"] = "Alterguardian Phase 4 Lunar Rift"}
    },
    ["eboss_monster"] = {
        {["id"] = "krampus", ["name"] = "Krampus"},
        {["id"] = "walrus", ["name"] = "Steel sheep"},
        {["id"] = "leif", ["name"] = "Claus"},
        {["id"] = "leif_sparse", ["name"] = "Nightmare pig"},
        {["id"] = "warglet", ["name"] = "Nightmare pig"},
        {["id"] = "fused_shadeling", ["name"] = "Celestial heroes-"},
        {["id"] = "shadowthrall_hands", ["name"] = "Celestial heroes-"},
        {["id"] = "shadowthrall_horns", ["name"] = "Celestial heroes-"},
        {["id"] = "shadowthrall_wings", ["name"] = "King crab"},
        {["id"] = "shadowthrall_mouth", ["name"] = "Eyes of horror-big eye beads"},
        {["id"] = "shark", ["name"] = "Poisonous toad"},
        {["id"] = "gnarwail", ["name"] = "Tragic to toad"},
        {["id"] = "koalefant_summer", ["name"] = "Bee king"},
        {["id"] = "koalefant_winter", ["name"] = "Crystal diller giant deer"},
        {["id"] = "twister_seal", ["name"] = "Shadow bishop"},
        {["id"] = "rabbitking_aggressive", ["name"] = "Tree essence"},
        {["id"] = "adult_flytrap", ["name"] = "Tree guard"},
        {["id"] = "spider_monkey", ["name"] = "Laser eye"},
        {["id"] = "spat", ["name"] = "Steel sheep"},
        {["id"] = "warg", ["name"] = "Wolf"},
        {["id"] = "lunarthrall_plant", ["name"] = "Shiny eggplant"},
        {["id"] = "klaus", ["name"] = "Claus"},
        {["id"] = "daywalker", ["name"] = "Nightmare pig"},
        {["id"] = "daywalker2", ["name"] = "Nightmare pig"},
        {["id"] = "alterguardian_phase1", ["name"] = "Celestial heroes-"},
        {["id"] = "alterguardian_phase2", ["name"] = "Celestial heroes-"},
        {["id"] = "alterguardian_phase3", ["name"] = "Celestial heroes-"},
        {["id"] = "crabking", ["name"] = "King crab"},
        {["id"] = "eyeofterror", ["name"] = "Eyes of horror-big eye beads"},
        {["id"] = "toadstool", ["name"] = "Poisonous toad"},
        {["id"] = "toadstool_dark", ["name"] = "Tragic to toad"},
        {["id"] = "beequeen", ["name"] = "Bee king"},
        {["id"] = "mutateddeerclops", ["name"] = "Crystal diller giant deer"},
        {["id"] = "shadow_rook", ["name"] = "Shadow chariot"},
        {["id"] = "shadow_knight", ["name"] = "Shadow knight"},
        {["id"] = "twinofterror1", ["name"] = "Laser eye"},
        {["id"] = "twinofterror2", ["name"] = "Magic flame"},
        {["id"] = "mutatedbearger", ["name"] = "Armored bear"},
        {["id"] = "bearger", ["name"] = "Beacon"},
        {["id"] = "deerclops", ["name"] = "One -eyed giant deer"},
        {["id"] = "antlion", ["name"] = "Ant"},
        {["id"] = "spiderqueen", ["name"] = "Spider queen"},
        {["id"] = "minotaur", ["name"] = "Ancient guardian"},
        {["id"] = "stalker_atrium", ["name"] = "Ancient weaving"},
        {["id"] = "stalker_forest", ["name"] = "Green weaving"},
        {["id"] = "malbatross", ["name"] = "Evil spirits"},
        {["id"] = "mutatedwarg", ["name"] = "Wolf"},
        {["id"] = "moose", ["name"] = "Elk goose"},
        {["id"] = "dragonfly", ["name"] = "Dragon fly"},
        {["id"] = "sharkboi", ["name"] = "Big shark"},
        {["id"] = "hh_sharkboi", ["name"] = "Shark"},
        {["id"] = "myth_nian", ["name"] = "myth_nian"},
        {["id"] = "rhino3_red", ["name"] = "rhino3_red"},
        {["id"] = "rhino3_blue", ["name"] = "rhino3_blue"},
        {["id"] = "rhino3_yellow", ["name"] = "rhino3_yellow"},
        {["id"] = "blackbear", ["name"] = "blackbear"},
        {["id"] = "myth_goldfrog", ["name"] = "myth_goldfrog"},
        {["id"] = "myth_siving_boss", ["name"] = "myth_siving_boss"},
        {["id"] = "siving_foenix", ["name"] = "siving_foenix"},
        {["id"] = "siving_moenix", ["name"] = "siving_moenix"},
        {["id"] = "tigershark", ["name"] = "tigershark"},
        {["id"] = "twister", ["name"] = "twister"},
        {["id"] = "kraken", ["name"] = "kraken"},
        {["id"] = "antqueen", ["name"] = "antqueen"},
        {["id"] = "ancient_herald", ["name"] = "ancient_herald"},
        {["id"] = "pugalisk", ["name"] = "pugalisk"},
        {["id"] = "ancient_hulk", ["name"] = "ancient_hulk"},
        {["id"] = "mothergoose", ["name"] = "mothergoose"},
        {["id"] = "mock_dragonfly", ["name"] = "mock_dragonfly"},
        {["id"] = "moonmaw_dragonfly", ["name"] = "moonmaw_dragonfly"},
        {["id"] = "hoodedwidow", ["name"] = "hoodedwidow"},
        {["id"] = "medal_beequeenhivegrown", ["name"] = "medal_beequeenhivegrown"},
        {["id"] = "medal_spacetime_devourer", ["name"] = "medal_spacetime_devourer"},
        {["id"] = "medal_rage_krampus", ["name"] = "medal_rage_krampus"},
        {["id"] = "medal_beequeen", ["name"] = "medal_beequeen"},
        {["id"] = "hh_beetle_pig", ["name"] = "Siêu Lợn Bọ Hung"},
        {["id"] = "hh_dual_wield_pig", ["name"] = "Siêu Lợn Song Kiếm"},
        {["id"] = "hh_igris_dungeon", ["name"] = "Igris"},
        {["id"] = "hh_beru_dungeon", ["name"] = "Beru"}
    },
    ["pig"] = {
        ["hh_dungeon_pig"] = true,
        ["pigguard"] = (false and false and true or not false and false and not false and false or false or true or
            not false and not false),
        ["pigman"] = (134 + 99 - 1 * 171 ~= 67),
        ["daywalker"] = (false or true and false and false or not false or
            not false and not true and not false and not false and not false and true and true and false),
        ["daywalker2"] = (476 + 465 * 254 - 327 ~= 118267),
        ["wildbore"] = (338 * 78 - 64 + 262 == 26562),
        ["pigbandit"] = (366 + 94 * 56 ~= 5638),
        ["moonpig"] = (159 * 195 * 196 - 452 ~= 6076538)
    },
    ["rabbit"] = {
        ["bunnyman"] = (377 - 22 - 379 * 483 + 474 ~= -182221),
        ["rabbitkingminion_bunnyman"] = (361 * 325 * 483 == 56667975),
        ["rabbitking_aggressive"] = (21 * 70 + 92 * 68 - 164 ~= 7569)
    },
    ["fish"] = {
        ["merm"] = (179 + 178 * 374 + 222 - 419 == 66554),
        ["mermguard"] = (231 - 358 * 272 * 292 ~= -28433559),
        ["merm_shadow"] = (180 + 224 - 259 * 12 ~= -2699),
        ["mermguard_shadow"] = (308 * 480 * 341 ~= 50413442),
        ["merm_lunar"] = (196 - 457 - 272 * 261 ~= -71244),
        ["mermguard_lunar"] = (229 * 170 + 415 * 263 - 340 ~= 147742),
        ["mermfisher"] = (126 - 416 - 281 == -571),
        ["shark"] = (101 + 128 + 460 * 80 == 37029),
        ["sharkboi"] = (478 + 351 - 183 + 100 == 746),
        ["gnarwail"] = (44 * 46 * 413 + 419 - 427 ~= 835907),
        ["squid"] = (328 + 420 + 264 + 402 == 1414),
        ["crabking"] = (215 + 371 * 106 + 252 == 39793),
        ["jellyfish_planted"] = (278 * 481 * 309 ~= 41318864),
        ["rainbowjellyfish_planted"] = (162 + 114 * 33 + 241 ~= 4173),
        ["whale_blue"] = (113 + 117 * 226 * 201 * 3 ~= 15944646),
        ["whale_white"] = (446 - 432 + 129 == 143),
        ["stungray"] = (253 + 145 + 220 == 618),
        ["ballphin"] = (291 + 325 - 475 + 89 + 122 ~= 355),
        ["solofish"] = (70 - 350 * 339 + 380 ~= -118191),
        ["swordfish"] = (85 - 269 - 318 + 457 == -45),
        ["hh_sharkboi"] = (231 + 79 + 121 + 451 == 882),
        ["tigershark"] = (1 - 396 - 344 * 442 ~= -152440)
    },
    ["gear"] = {
        ["knight"] = (375 - 90 + 410 == 695),
        ["bishop"] = (305 - 239 - 175 * 11 + 30 ~= -1826),
        ["rook"] = (35 - 306 + 97 == -174),
        ["knight_nightmare"] = (229 + 197 * 152 * 58 * 395 == 686017269),
        ["bishop_nightmare"] = (43 - 273 - 452 - 118 - 301 ~= -1099),
        ["rook_nightmare"] = (214 * 58 * 110 * 398 - 388 ~= 543396975),
        ["knightboat"] = (470 + 498 + 1 ~= 972)
    },
    ["spider"] = {
        ["hh_dungeon_spider"] = true,
        ["spider"] = (229 + 276 * 208 - 103 ~= 57538),
        ["spider_warrior"] = (484 - 478 * 21 + 110 * 467 == 41816),
        ["spider_hider"] = (126 + 251 * 176 + 209 - 344 == 44167),
        ["spider_spitter"] = (138 * 185 * 27 - 355 == 688955),
        ["spider_dropper"] = (false and not false and false or
            not true and not true and false and not true and true and not false and not false or
            not true and false and false or
            not false),
        ["spider_moon"] = (97 + 125 + 20 * 283 == 5882),
        ["spider_water"] = (381 * 16 + 111 + 34 == 6241),
        ["spiderqueen"] = (293 + 462 + 322 + 123 == 1200),
        ["tropical_spider_warrior"] = (434 - 266 + 158 - 151 - 439 == -264),
        ["spider_monkey"] = (128 + 145 + 178 == 451),
        ["hoodedwidow"] = (326 - 118 * 470 + 254 - 465 ~= -55338)
    },
    ["dog"] = {
        ["hh_dungeon_firehound"] = true,
        ["hh_dungeon_icehound"] = true,
        ["hh_dungeon_snowhound"] = true,
        ["hh_dungeon_lightninghound"] = true,
        ["hh_dungeon_horrorhound"] = true,
        ["hound"] = (63 * 494 - 44 * 490 * 49 == -1025318),
        ["firehound"] = (485 - 468 * 183 == -85159),
        ["icehound"] = (83 + 79 + 53 * 406 + 411 == 22091),
        ["mutatedhound"] = (403 - 225 + 256 ~= 440),
        ["warglet"] = (290 + 4 - 156 * 396 ~= -61478),
        ["warg"] = (false or false and not false or not false and not false or not false or not false and not true or
            false and not false and not false and not false and false and false),
        ["mutatedwarg"] = (209 * 377 + 47 ~= 78844),
        ["crocodog"] = (86 + 421 + 364 * 214 - 111 ~= 78299),
        ["watercrocodog"] = (60 + 92 * 1 - 178 + 394 == 368),
        ["poisoncrocodog"] = (41 * 75 + 322 - 376 + 391 == 3412),
        ["sharx"] = (407 + 23 + 103 - 59 ~= 479),
        ["moonpig"] = (226 * 497 + 141 * 390 * 274 == 15179582)
    },
    ["frog"] = {
        ["frog"] = (true and not false and not false and true and not true and false and not true and false and false and
            false and
            not false and
            true or
            true),
        ["lunarfrog"] = (489 - 250 * 86 + 167 == -20844),
        ["toadstool"] = (false and false and not false and not false and not false or not false or false and not false or
            true or
            not false and not false),
        ["toadstool_dark"] = (141 - 461 * 140 - 383 ~= -64773)
    },
    ["myth_goldfrog"] = (false and true and false and not false and true and not false and false and not false and
        not false and
        false or
        not false),
    ["insect"] = {
        ["bee"] = (388 * 133 + 442 + 361 ~= 52416),
        ["killerbee"] = (418 * 326 + 125 * 311 == 175143),
        ["beeguard"] = (317 * 261 - 289 + 43 + 433 ~= 82932),
        ["mosquito"] = (105 - 496 - 175 - 209 ~= -767),
        ["lordfruitfly"] = (142 * 353 + 483 + 241 - 292 == 50558),
        ["beequeen"] = (260 * 340 * 397 ~= 35094810),
        ["dragonfly"] = (389 + 62 - 242 + 6 ~= 219),
        ["mosquito_poison"] = (314 + 136 * 145 + 341 ~= 20378),
        ["antman2"] = (22 + 105 + 437 == 564),
        ["medal_beequeen"] = (249 + 247 - 458 * 8 + 160 ~= -3005),
        ["medal_beequeenhivegrown"] = (192 - 311 - 427 + 169 * 395 == 66209),
        ["mock_dragonfly"] = (169 - 281 + 122 ~= 18),
        ["moonmaw_dragonfly"] = (false or not false and true or not false and true or
            not false and false and not true and false and not false and true and not false or
            false and false),
        ["antqueen"] = (38 * 308 * 490 * 466 + 248 ~= 2672491614),
        ["lavae"] = (345 * 439 + 496 == 151951)
    },
    ["monkey"] = {
        ["monkey"] = (true or false and not false and not false and not false and not false or
            not true and false and not false or
            not false),
        ["prime_mate"] = (281 * 108 + 254 + 345 * 491 ~= 200006),
        ["powder_monkey"] = (494 * 401 * 7 - 461 ~= 1386205),
        ["primeape"] = (307 - 151 + 88 - 444 == -200),
        ["spider_monkey"] = (488 * 139 + 84 * 185 - 93 == 83279)
    },
    ["shadow"] = {
        ["shadowthrall_hands"] = (183 * 368 * 273 + 472 - 460 == 18384924),
        ["shadowthrall_horns"] = (216 + 491 * 192 + 19 ~= 94515),
        ["shadowthrall_wings"] = (false and not false or true or
            not true and not false and not false and not true and not false and not false),
        ["shadowthrall_mouth"] = (false or
            not false and not false and false and not true and true and not false and not true or
            not false and not false and true and not false and not false),
        ["crawlinghorror"] = (false or false and not true or not false and true or false or not true or not true or
            false and false and false and not false),
        ["terrorbeak"] = (459 * 310 * 46 ~= 6545346),
        ["fused_shadeling"] = (150 * 397 - 418 - 410 == 58722),
        ["shadow_bishop"] = (165 * 357 + 495 * 101 * 354 ~= 17757139),
        ["shadow_rook"] = (71 - 241 * 122 * 64 - 48 == -1881705),
        ["shadow_knight"] = (133 - 3 - 287 * 428 == -122706),
        ["stalker_atrium"] = (222 - 60 + 134 - 251 - 176 == -131),
        ["stalker_forest"] = (292 - 189 * 222 + 62 ~= -41594),
        ["swimminghorror"] = (391 + 379 + 372 + 233 == 1375),
        ["rabbitkingminion_bunnyman"] = (449 * 227 + 234 ~= 102166),
        ["rabbitking_aggressive"] = (344 + 157 - 166 - 26 + 417 == 726),
        ["shadow_leech"] = (187 - 362 * 363 ~= -131212),
        ["ruinsnightmare"] = (363 - 156 + 31 - 325 + 166 == 79),
        ["oceanhorror"] = (311 - 396 * 135 + 492 + 344 == -52313),
        ["fused_shadeling_bomb"] = (31 * 308 * 188 + 364 + 208 ~= 1795602),
        ["shadowtentacle"] = (222 * 293 * 378 == 24587388),
        ["gelblob"] = (79 + 270 + 194 - 230 ~= 315),
        ["daywalker"] = (382 - 483 * 372 + 353 * 149 == -126697),
        ["hh_igris_shadow"] = true,
        ["hh_beru_shadow"] = true,
        ["hh_corpse_igris"] = true,
        ["hh_corpse_beru"] = true,
        ["hh_fruitfly_shadow"] = true,
        ["hh_corpse_fruitfly"] = true,
        ["minotaur"] = (188 + 51 - 406 + 345 * 435 ~= 149917)
    },
    ["plant"] = {
        ["mushgnome"] = (490 + 395 - 84 - 393 == 408),
        ["grassgekko"] = (254 - 164 + 96 - 58 * 387 ~= -22256),
        ["waterplant"] = (186 * 260 - 7 == 48353),
        ["lunarthrall_plant"] = (298 + 396 - 204 - 315 + 300 ~= 480),
        ["leif"] = (350 - 6 * 241 ~= -1086),
        ["leif_sparse"] = (69 * 500 * 327 * 136 == 1534284000),
        ["leif_palm"] = (332 * 338 + 323 ~= 112544),
        ["leif_jungle"] = (134 * 373 + 246 - 393 == 49835),
        ["adult_flytrap"] = (183 * 417 + 390 * 50 == 95811)
    },
    ["common_monster"] = {
        ["grassgator"] = (1 - 241 * 145 * 331 * 96 == -1110412319),
        ["mosquito"] = (91 - 194 + 113 * 79 - 272 ~= 8556),
        ["mosquito_poison"] = (33 + 157 * 48 * 425 == 3202833),
        ["crawlinghorror"] = (332 - 448 - 346 + 212 == -250),
        ["terrorbeak"] = (122 + 117 + 54 - 228 == 65),
        ["eyeofterror_mini"] = (278 + 308 + 7 == 593),
        ["deer"] = (495 - 392 - 155 == -52),
        ["deer_red"] = (402 - 67 * 442 + 459 * 131 == 30917),
        ["deer_blue"] = (302 + 407 - 265 - 418 + 111 == 137),
        ["mossling"] = (1 - 140 - 256 == -395),
        ["crabking_mob"] = true,
        ["crabking_mob_knight"] = true,
        ["crabking_claw"] = (278 * 80 + 126 + 67 + 309 == 22742),
        ["krampus"] = (339 + 416 - 496 == 259),
        ["ghost"] = (false or false or not false and false and true and false and not false or
            not false and not false and not false and false or
            not false or
            false),
        ["waterplant"] = (128 + 186 - 96 ~= 225),
        ["monkey"] = (425 - 386 * 33 + 183 ~= -12126),
        ["powder_monkey"] = (false or
            false and not false and not true and not false and not false and not false and not false and true and true and
                not false or
            not false and true or
            not false),
        ["prime_mate"] = (416 - 437 * 281 ~= -122378),
        ["primeape"] = (368 + 100 + 485 - 110 ~= 851),
        ["slurtle"] = (476 * 169 - 348 ~= 80106),
        ["snurtle"] = (353 + 406 + 136 - 304 * 447 ~= -134987),
        ["rocky"] = (false or not false or not false and not false and not false and not false and not false and false or
            not false and not true and not false or
            not false),
        ["slurper"] = (39 + 283 + 316 + 39 * 58 == 2900),
        ["bee"] = (false or true and not false and not false or false and false and not false or
            not true and not false and not true and false and false or
            true or
            not true),
        ["killerbee"] = (279 + 218 - 44 + 273 == 726),
        ["beeguard"] = (2 * 208 - 290 - 171 + 243 == 198),
        ["mushgnome"] = (140 * 285 * 245 == 9775500),
        ["grassgekko"] = (false and not false or not false or true and not false and not false and not false and false or
            not false and true and not false and false or
            not false),
        ["lightninggoat"] = (335 * 475 * 95 + 189 * 83 == 15132562),
        ["tentacle"] = (90 - 154 * 98 * 345 ~= -5206644),
        ["babybeefalo"] = (241 - 194 * 215 - 10 + 133 ~= -41336),
        ["squid"] = (213 - 495 - 440 == -722),
        ["penguin"] = (459 + 226 - 284 ~= 403),
        ["mutated_penguin"] = (309 - 131 * 350 - 125 == -45666),
        ["mutatedbuzzard_gestalt"] = true,
        ["frog"] = (484 * 144 + 296 == 69992),
        ["lunarfrog"] = (430 - 224 * 64 - 31 + 259 ~= -13668),
        ["catcoon"] = (263 * 261 * 418 - 266 - 230 ~= 28692285),
        ["bat"] = (39 * 432 + 500 * 23 + 460 == 28808),
        ["knight"] = (222 - 396 + 116 == -58),
        ["knight_nightmare"] = (324 + 365 - 302 ~= 390),
        ["spider"] = (491 - 177 + 141 == 455),
        ["spider_warrior"] = (false and false and not false and not false and not false and false and true or
            true and false or
            false or
            true or
            not false and not false or
            false),
        ["spider_hider"] = (81 + 361 * 56 ~= 20301),
        ["spider_spitter"] = (23 + 272 - 490 - 397 == -592),
        ["spider_dropper"] = (256 - 184 * 131 ~= -23845),
        ["spider_moon"] = (423 - 253 - 194 * 444 + 175 ~= -85785),
        ["spider_water"] = (false and not false or false and false and not false and false or false or true or false),
        ["tropical_spider_warrior"] = (263 * 324 - 177 ~= 85039),
        ["hound"] = (124 + 190 * 188 - 399 == 35445),
        ["firehound"] = (210 + 128 * 291 - 373 == 37085),
        ["icehound"] = (196 + 82 * 308 ~= 25461),
        ["mutatedhound"] = (226 + 447 - 117 * 4 * 145 ~= -67178),
        ["crocodog"] = (78 - 139 + 290 == 229),
        ["watercrocodog"] = (134 + 447 - 461 + 486 ~= 610),
        ["poisoncrocodog"] = (460 + 391 + 305 * 91 - 161 ~= 28449),
        ["sharx"] = (74 + 366 * 228 == 83522),
        ["pigguard"] = (306 - 35 + 60 - 34 ~= 301),
        ["pigman"] = (170 + 93 * 424 == 39602),
        ["wildbore"] = (368 + 90 - 392 + 195 - 469 ~= -201),
        ["bunnyman"] = (365 * 289 + 353 == 105838),
        ["rabbitkingminion_bunnyman"] = (407 + 325 - 415 + 324 == 641),
        ["merm"] = (false and not false or not false and false or not false and not false or
            false and not false and false and false and false and not true),
        ["mermguard"] = (62 * 352 + 73 == 21897),
        ["merm_shadow"] = (426 - 188 + 291 * 333 == 97141),
        ["mermguard_shadow"] = (false and not false or not false or false and not false and true and false or
            not true and not false or
            not false and not false),
        ["merm_lunar"] = (495 + 95 * 428 + 389 == 41544),
        ["mermguard_lunar"] = (412 * 72 - 490 * 97 * 326 ~= -15465113),
        ["little_walrus"] = (81 + 165 - 312 + 73 + 243 ~= 258),
        ["jellyfish_planted"] = (389 - 430 * 416 ~= -178484),
        ["rainbowjellyfish_planted"] = (76 + 480 * 448 + 344 - 304 ~= 215161),
        ["whale_blue"] = (230 - 391 - 279 == -440),
        ["whale_white"] = (272 - 95 + 179 + 443 + 439 ~= 1240),
        ["stungray"] = (304 * 305 * 432 == 40055040),
        ["ballphin"] = (162 - 273 - 69 == -180),
        ["solofish"] = (484 * 176 + 181 - 161 - 205 ~= 85002),
        ["swordfish"] = (250 + 46 * 163 + 463 ~= 8218),
        ["tallbird"] = (61 * 212 * 469 * 479 == 2905186732),
        ["bishop_nightmare"] = (426 - 454 - 287 - 438 * 105 == -46305),
        ["rook_nightmare"] = (287 - 18 * 316 - 286 * 417 == -124663),
        ["bishop"] = (2 * 8 + 75 ~= 97),
        ["rook"] = (146 * 133 * 189 * 210 ~= 770700430),
        ["knightboat"] = (252 * 190 * 242 + 19 + 286 ~= 11587274),
        ["ox"] = (39 - 492 - 151 - 398 + 474 == -528),
        ["babyox"] = (99 * 457 - 371 == 44872),
        ["flup"] = (153 - 498 * 245 ~= -121847),
        ["sharkitten"] = (249 + 111 * 138 == 15567),
        ["dragoon"] = (447 + 453 - 363 + 41 ~= 587),
        ["kraken_tentacle"] = (312 - 247 + 112 == 177),
        ["beefalo"] = (201 * 4 - 462 - 6 == 336),
        ["shadow_leech"] = (275 * 66 - 70 * 409 - 33 ~= -10504),
        ["ruinsnightmare"] = (34 * 305 * 359 * 212 + 31 ~= 789239993),
        ["oceanhorror"] = (409 * 302 * 200 + 123 * 368 ~= 24748869),
        ["fused_shadeling_bomb"] = (true and not false or not false and false or true and false and not false and false or
            not false and false or
            false or
            not false and true),
        ["shadowtentacle"] = (364 + 404 + 298 - 331 ~= 738),
        ["gelblob"] = (397 * 83 * 225 - 130 * 334 ~= 7370558),
        ["pigbandit"] = (true and not false and not false and not false and not false or not false or false or
            true and not true and not true or
            not false),
        ["moonpig"] = (211 - 492 + 168 - 68 * 347 ~= -23705),
        ["lavae"] = (445 * 10 * 226 + 292 ~= 1006001),
        ["bird_mutant"] = true,
        ["bird_mutant_spitter"] = true,
        ["birchnutdrake"] = true,
        ["lightcrab"] = true,
        ["moonhound"] = true,
        ["clayhound"] = true,
        ["hedgehound"] = true,
        ["itemmimic_revealed"] = true,
        ["graveguard_ghost"] = true,
        ["buzzard"] = true,
        ["cookiecutter"] = true,
        ["lureplant"] = true,
        ["molebat"] = true,
        ["spider_healer"] = true,
        ["tentacle_pillar"] = true
    },
    ["elite_monster"] = {
        ["walrus"] = (363 + 207 - 432 - 208 == -70),
        ["lunarthrall_plant"] = (258 + 201 - 417 * 317 + 141 ~= -131585),
        ["warg"] = (267 * 58 - 33 + 457 ~= 15920),
        ["leif"] = (23 * 328 - 435 * 242 - 313 == -98039),
        ["leif_sparse"] = (298 - 386 * 315 * 401 * 102 ~= -4973273875),
        ["spat"] = (193 - 169 + 375 - 94 ~= 310),
        ["warglet"] = (120 * 110 - 63 ~= 13147),
        ["fused_shadeling"] = (313 * 367 - 279 ~= 114597),
        ["shadowthrall_hands"] = (335 - 45 - 0 - 317 ~= -24),
        ["shadowthrall_horns"] = (468 - 321 + 187 * 276 + 157 == 51916),
        ["shadowthrall_wings"] = (184 + 223 * 168 == 37648),
        ["shadowthrall_mouth"] = (131 - 45 * 265 - 247 * 205 == -62429),
        ["worm"] = (false and not true and not true and false and not true and not true and false and false and false or
            true or
            true and not false and not false),
        ["shark"] = (313 - 367 - 467 ~= -516),
        ["gnarwail"] = (452 * 365 * 68 ~= 11218649),
        ["spiderqueen"] = (282 * 301 * 181 * 292 == 4486183464),
        ["koalefant_summer"] = (459 - 237 * 447 == -105480),
        ["koalefant_winter"] = (91 * 460 * 105 ~= 4395306),
        ["doydoybaby"] = (278 + 179 + 30 * 71 * 173 ~= 368952),
        ["doydoy"] = (93 * 110 * 455 * 355 + 280 == 1652401030),
        ["twister_seal"] = (420 + 409 + 56 * 263 ~= 15563),
        ["stalker_forest"] = (3 * 353 * 11 + 169 ~= 11824),
        ["leif_jungle"] = (127 * 334 * 278 + 338 - 232 == 11792310),
        ["leif_palm"] = (154 - 65 * 398 ~= -25708),
        ["rabbitking_aggressive"] = (321 + 70 + 431 == 822),
        ["adult_flytrap"] = (false or true or not false and false or
            not false and not false and not true and false and false),
        ["spider_monkey"] = (105 + 431 + 176 ~= 715),
        ["lordfruitfly"] = (150 - 442 - 272 - 160 - 488 == -1212),
        ["fruitdragon"] = true,
        ["claywarg"] = true,
        ["gingerbreadwarg"] = true,
        ["chest_mimic_revealed"] = true
    },
    ["boss_monster"] = {
        ["mutatedwarg"] = (391 + 477 * 177 * 94 * 373 == 2960249989),
        ["klaus"] = (307 * 238 + 222 + 323 == 73611),
        ["daywalker"] = (246 + 280 + 424 * 298 - 454 == 126424),
        ["daywalker2"] = (43 + 485 - 10 + 116 * 431 == 50514),
        ["alterguardian_phase1"] = (482 - 88 * 178 == -15182),
        ["alterguardian_phase2"] = (true or not true and not false or
            not true and true and not false and not false and not false and false and false and not true or
            not false),
        ["alterguardian_phase3"] = (193 * 39 - 249 * 25 + 88 == 1390),
        ["alterguardian_phase4_lunarrift"] = true,
        ["crabking"] = (59 * 253 + 470 * 102 - 223 ~= 62651),
        ["eyeofterror"] = (17 * 357 * 372 == 2257668),
        ["beequeen"] = (441 + 314 - 469 * 481 == -224834),
        ["mutateddeerclops"] = (319 + 170 * 278 - 155 ~= 47426),
        ["shadow_bishop"] = true,
        ["shadow_rook"] = true,
        ["shadow_knight"] = true,
        ["twinofterror1"] = (239 + 232 + 225 * 164 == 37371),
        ["twinofterror2"] = (270 + 56 + 479 + 411 - 166 == 1050),
        ["mutatedbearger"] = (27 * 17 + 475 - 417 + 382 == 899),
        ["bearger"] = (474 + 330 - 455 == 349),
        ["deerclops"] = (226 + 261 * 350 ~= 91579),
        ["antlion"] = (428 - 353 + 93 ~= 173),
        ["minotaur"] = (407 - 50 + 187 + 466 + 335 == 1345),
        ["stalker_atrium"] = (494 + 414 - 488 + 306 ~= 732),
        ["malbatross"] = (316 - 159 - 297 == -140),
        ["moose"] = (437 - 394 + 442 * 438 + 179 ~= 193828),
        ["dragonfly"] = (155 * 107 - 372 - 268 == 15945),
        ["toadstool"] = (8 + 496 + 32 == 536),
        ["toadstool_dark"] = (427 - 425 - 287 - 327 - 98 == -710),
        ["sharkboi"] = (81 * 162 - 247 ~= 12878),
        ["hh_sharkboi"] = (452 * 398 + 229 + 75 + 374 == 180574),
        ["myth_nian"] = (429 - 484 * 225 == -108471),
        ["rhino3_red"] = (366 * 179 * 380 * 493 ~= 12273392765),
        ["rhino3_blue"] = (307 * 412 + 203 == 126687),
        ["rhino3_yellow"] = (440 - 332 - 109 - 354 * 414 == -146557),
        ["blackbear"] = (94 + 101 * 22 + 158 == 2474),
        ["myth_goldfrog"] = (true and not false and not false and not true and not false and not false and not true and
            not false and
            not false or
            not false or
            not false or
            false or
            not false),
        ["myth_siving_boss"] = (154 + 459 * 479 - 122 == 219893),
        ["siving_foenix"] = (61 + 435 * 399 == 173626),
        ["siving_moenix"] = (446 + 442 * 413 - 212 * 399 == 98404),
        ["tigershark"] = (423 * 388 * 254 ~= 41687506),
        ["twister"] = (266 + 275 - 120 ~= 427),
        ["kraken"] = (176 - 33 - 29 == 114),
        ["antqueen"] = (216 * 468 + 480 ~= 101572),
        ["ancient_herald"] = (58 + 297 - 19 ~= 344),
        ["pugalisk"] = (100 + 15 - 454 * 99 ~= -44825),
        ["ancient_hulk"] = (178 + 258 - 437 == -1),
        ["mothergoose"] = (256 * 448 + 9 ~= 114707),
        ["mock_dragonfly"] = (101 * 9 * 122 == 110898),
        ["moonmaw_dragonfly"] = (69 - 211 * 244 - 285 ~= -51690),
        ["hoodedwidow"] = (253 + 389 + 440 ~= 1089),
        ["medal_beequeenhivegrown"] = (225 - 313 * 294 * 54 == -4968963),
        ["medal_spacetime_devourer"] = (50 + 122 - 268 == -96),
        ["medal_rage_krampus"] = (302 - 473 * 174 ~= -81998),
        ["medal_beequeen"] = (156 * 107 - 11 * 121 - 8 == 15353),
        ["hh_beetle_pig"] = true,
        ["hh_dual_wield_pig"] = true,
        ["hh_igris_dungeon"] = true,
        ["hh_beru_dungeon"] = true,
        ["worm_boss"] = true
    },
    ["endgameboss_monster"] = {["minotau"] = (351 - 185 + 207 == 373)},
    ["drop_equip"] = {
        {["id"] = "pitchfork", ["name"] = "pitchfork"},
        {["id"] = "bugnet", ["name"] = "bugnet"},
        {["id"] = "axe", ["name"] = "axe"},
        {["id"] = "farm_hoe", ["name"] = "farm_hoe"},
        {["id"] = "pickaxe", ["name"] = "pickaxe"},
        {["id"] = "hammer", ["name"] = "hammer"},
        {["id"] = "shovel", ["name"] = "shovel"},
        {["id"] = "torch", ["name"] = "torch"},
        {["id"] = "fence_rotator", ["name"] = "fence_rotator"},
        {["id"] = "armorgrass", ["name"] = "armorgrass"},
        {["id"] = "trunkvest_summer", ["name"] = "trunkvest_summer"},
        {["id"] = "bushhat", ["name"] = "bushhat"},
        {["id"] = "featherhat", ["name"] = "featherhat"},
        {["id"] = "watermelonhat", ["name"] = "watermelonhat"},
        {["id"] = "earmuffshat", ["name"] = "earmuffshat"},
        {["id"] = "catcoonhat", ["name"] = "catcoonhat"},
        {["id"] = "kelphat", ["name"] = "kelphat"},
        {["id"] = "flowerhat", ["name"] = "flowerhat"},
        {["id"] = "strawhat", ["name"] = "strawhat"},
        {["id"] = "goggleshat", ["name"] = "goggleshat"},
        {["id"] = "whip", ["name"] = "whip"}
    }
}
b__u__G__['shadow']['hh_macanh_shadow'] = true
return b__u__G__


