-- Only for the disposable offline audit server; does not use live player saves.
local ok, err = pcall(function()
    assert(TheWorld.ismastersim)
    assert(TheWorld.components.hh_world, "host world component missing")
    assert(Prefabs.eva and Prefabs.ttk_hhlmz and Prefabs.hh_daogam)
    local portal = TheSim:FindFirstEntityWithTag("multiplayer_portal")
    local x,y,z = portal.Transform:GetWorldPosition()
    local p = assert(SpawnPrefab("eva"))
    p.Transform:SetPosition(x,y,z)
    local souls = assert(p.components.eva_souls)
    assert(p.components.hh_leveling, "host player progression missing")
    assert(souls.level == 1 and souls.current == 100)
    p.components.hh_leveling.level = 151 -- Disposable fixture uses unified progression.
    p:PushEvent("hh_levelup")
    assert(souls.level == 151 and souls.max == 1000)
    souls:DoDelta(1000)
    p.components.health:SetInvincible(true)
    local target = assert(SpawnPrefab("spider"))
    target.Transform:SetPosition(x + 1.5,y,z)
    target.components.health:SetMaxHealth(100000)
    target.components.health:SetPercent(1)
    target:StopBrain()
    local took_damage = false
    target:ListenForEvent("healthdelta", function(_, data)
        if data.oldpercent > data.newpercent then took_damage = true end
    end)
    local weapon = assert(SpawnPrefab("eva_scythe"))
    p.components.inventory:Equip(weapon)
    p:DoTaskInTime(1, function()
        local success, problem = pcall(function()
            assert(p._eva_skillbook_entity, "hidden spellbook missing")
            local before = souls.current
            assert(p.components.eva_wings:Enable())
            assert(p.components.eva_wings:Disable(true))
            assert(p.components.eva_life:Activate())
            assert(p.components.eva_harvest:CastAt(x,z))
            assert(p.components.eva_scythe_array:CastAt(x,z))
            assert(souls.current == before - 213, "skill costs changed")
            assert(p.components.eva_daydu:CastAt(x+1.5,z))
            assert(souls.current == before - 218, "daydu cost changed")
            p.components.combat:DoAttack(target)
            assert(p.components.eva_melee_wave.hit_count == 1, "first melee hit missing")
            p.components.combat:DoAttack(target)
            assert(p.components.eva_melee_wave.hit_count == 0
                and next(p.components.eva_melee_wave.waves) ~= nil, "second hit wave missing")
            print("EVA_ACTIVE_SKILLS_STARTED")
        end)
        if not success then print("EVA_SMOKE_FAIL",problem) end
    end)
    p:DoTaskInTime(4, function()
        local success, problem = pcall(function()
            assert(p.components.eva_fox_blink:CastAt(x,z+2))
            print("EVA_FOX_STARTED")
        end)
        if not success then print("EVA_SMOKE_FAIL",problem) end
    end)
    p:DoTaskInTime(18, function()
        local success, problem = pcall(function()
            assert(not p.components.eva_life.active, "life did not expire")
            assert(p.components.eva_harvest.controller == nil, "harvest leaked")
            assert(p.components.eva_scythe_array.controller == nil, "array leaked")
            assert(not p.components.eva_fox_blink.active, "fox state leaked")
            assert(took_damage, "damage missing")
            local saved = souls:OnSave()
            assert(saved.level == 151)
            p:Remove()
            target:Remove()
            print("EVA_SMOKE_PASS")
        end)
        if not success then print("EVA_SMOKE_FAIL",problem) end
    end)
end)
if not ok then print("EVA_SMOKE_FAIL",err) end
